<?php

/**
 * @file
 * Allows store owners to create links to add products to carts and send
 * customers on to checkout.
 */

/**
 * Implements hook_help().
 */
function uc_cart_links_help($section = 'admin/help#uc_cart_links', $arg = NULL) {
  switch ($section) {
    case 'admin/store/settings/cart-links':
      return '<p>' . t('<a href="!url">View the help page</a> to learn how to create Cart Links.', array('!url' => url('admin/help/uc_cart_links'))) . '</p>';
    case 'admin/help#uc_cart_links':
    case 'admin/help/cart-links':
      $build = \Drupal\uc_cart_links\Controller\CartLinksHelp::creationHelp();
      return drupal_render($build);
  }
}

/**
 * Implements hook_permission().
 */
function uc_cart_links_permission() {
  return array(
    'administer cart links' => array(
      'title' => t('Administer cart links'),
    ),
    'view cart links report' => array(
      'title' => t('View cart links report'),
    ),
  );
}

/**
 * Implements hook_uc_add_to_cart().
 */
function uc_cart_links_uc_add_to_cart($nid, $qty, $data) {
  if (\Drupal::currentUser()->hasPermission('administer cart links') &&
      \Drupal::config('uc_cart_links.settings')->get('add_show')) {
    $cart_link = 'p' . $nid . '_q' . $qty;
    if (!empty($data['attributes'])) {
      foreach ($data['attributes'] as $attribute => $option) {
        if (is_array($option)) {
          // Checkbox options are stored in an array.
          foreach ($option as $oid => $ovalue) {
            if ($ovalue != 0) {
              $cart_link .= '_a' . $attribute . 'o' . $oid;
            }
          }
        }
        else {
          // Textfield, Select, or Radio options.
          $cart_link .= '_a' . $attribute . 'o' . $option;
        }
      }
    }
    drupal_set_message(t('Cart Link product action: @cart_link', array('@cart_link' => $cart_link)));
  }
}
