<?php

/**
 * @file
 * Shipping quote module that defines a weight-based shipping rate for each
 * product.
 */

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Url;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Adds a form element for the shipping rate of a product.
 */
function uc_weightquote_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (uc_product_is_product_form($form)) {
    $quote_config = \Drupal::config('uc_quote.settings');
    $weight = $quote_config->get('method_weight');
    $result = db_query("SELECT mid, title, product_rate FROM {uc_weightquote_methods}");
    foreach ($result as $method) {
      // Ensure the default weight is set.
      $weight += array('weightquote_' . $method->mid => 0);

      if (!isset($form['shipping']['weightquote'])) {
        $form['shipping']['weightquote'] = array(
          '#type' => 'details',
          '#title' => t('Shipping rates by weight'),
          '#description' => t("Overrides the default shipping rate per product for each flat rate shipping method. Leave field empty to use the method's default value."),
          '#tree' => TRUE,
          '#weight' => 0,
        );
      }
      $unit = \Drupal::config('uc_store.settings')->get('units.weight');
      $form['shipping']['weightquote'][$method->mid] = array(
        '#type' => 'uc_price',
        '#title' => SafeMarkup::checkPlain($method->title),
        '#default_value' => isset($form['#node']->weightquote[$method->mid]) ? $form['#node']->weightquote[$method->mid] : '',
        '#description' => t('Default rate: %price per @unit', array('%price' => uc_currency_format($method->product_rate), '@unit' => $unit)),
        '#field_suffix' => t('per @unit', array('@unit' => $unit)),
        '#weight' => $weight['weightquote_' . $method->mid],
        '#empty_zero' => FALSE,
      );
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function uc_weightquote_node_insert($node) {
  uc_weightquote_node_update($node);
}

/**
 * Implements hook_node_update().
 */
function uc_weightquote_node_update($node) {
  if (uc_product_is_product($node)) {
    if (isset($node->weightquote) && is_array($node->weightquote)) {
      if (!$node->isNewRevision()) {
        db_delete('uc_weightquote_products')
          ->condition('vid', $node->getRevisionId())
          ->execute();
      }

      $query = db_insert('uc_weightquote_products')
        ->fields(array('vid', 'nid', 'mid', 'rate'));

      foreach ($node->weightquote as $mid => $rate) {
        if (is_numeric($rate) && $rate >= 0) {
          $query->values(array(
              'vid' => $node->getRevisionId(),
              'nid' => $node->id(),
              'mid' => $mid,
              'rate' => $rate,
            ));
        }
      }

      $query->execute();
    }
  }
}

/**
 * Implements hook_node_load().
 */
function uc_weightquote_node_load($nodes) {
  $vids = array();
  foreach ($nodes as $node) {
    if (uc_product_is_product($node)) {
      $vids[$node->id()] = $node->getRevisionId();
    }
  }

  if ($vids) {
    $result = db_query("SELECT nid, mid, rate FROM {uc_weightquote_products} WHERE vid IN (:vids[])", array(':vids[]' => $vids));
    foreach ($result as $method) {
      $nodes[$method->nid]->weightquote[$method->mid] = $method->rate;
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function uc_weightquote_node_delete($node) {
  db_delete('uc_weightquote_products')
    ->condition('nid', $node->id())
    ->execute();
}

/**
 * Implements hook_node_revision_delete().
 */
function uc_weightquote_node_revision_delete($node) {
  db_delete('uc_weightquote_products')
    ->condition('vid', $node->getRevisionId())
    ->execute();
}

/**
 * Implements hook_uc_shipping_method().
 */
function uc_weightquote_uc_shipping_method() {
  $methods = array();

  $result = db_query("SELECT mid, title, label, base_rate, product_rate FROM {uc_weightquote_methods}");
  foreach ($result as $method) {
    $methods['weightquote_' . $method->mid] = array(
      'id' => 'weightquote_' . $method->mid,
      'module' => 'uc_weightquote',
      'title' => $method->title,
      'description' => t('!base_rate + !product_rate per !unit', array('!base_rate' => uc_currency_format($method->base_rate), '!product_rate' => uc_currency_format($method->product_rate), '!unit' => \Drupal::config('uc_store.settings')->get('units.weight'))),
      'operations' => array(
        'edit' => array(
          'title' => t('edit'),
          'url' => new Url('uc_weightquote.edit', ['mid' => $method->mid]),
        ),
        'delete' => array(
          'title' => t('delete'),
          'url' => new Url('uc_weightquote.delete', ['mid' => $method->mid]),
        ),
      ),
      'quote' => array(
        'type' => 'order',
        'callback' => 'uc_weightquote_quote',
        'accessorials' => array(
          $method->label,
        ),
      ),
      'enabled' => TRUE,
    );
  }

  return $methods;
}

/**
 * Standard callback to return a shipping rate via the weight quote method.
 *
 * @param $products
 *   The order's products.
 * @param $details
 *   Other order details including a shipping address.
 * @param $method
 *   The shipping method to use to create the quote.
 *
 * @return
 *   An array containing the shipping quote for the order.
 */
function uc_weightquote_quote($products, $details, $method) {
  $method = explode('_', $method['id']);
  $mid = $method[1];

  if ($method = db_query("SELECT * FROM {uc_weightquote_methods} WHERE mid = :mid", array(':mid' => $mid))->fetchObject()) {
    // Start at the base rate.
    $rate = $method->base_rate;

    foreach ($products as $product) {
      if (!isset($product->weightquote[$mid])) {
        // Add the method's default product rate.
        $product_rate = $method->product_rate * $product->qty->value;
      }
      else {
        // Add the product-specific rate.
        $product_rate = $product->weightquote[$mid] * $product->qty->value;
      }
      $rate += $product_rate  * $product->weight->value * uc_weight_conversion($product->weight->units);
    }

    $quotes[] = array(
      'rate' => $rate,
      'label' => SafeMarkup::checkPlain($method->label),
      'option_label' => SafeMarkup::checkPlain($method->label),
    );
  }

  return $quotes;
}
