<?php

/**
 * @file
 * Grants roles upon accepted payment of products.
 *
 * The uc_roles module will grant specified roles upon purchase of specified
 * products. Granted roles can be set to have a expiration date. Users can also
 * be notified of the roles they are granted and when the roles will
 * expire/need to be renewed/etc.
 */

use Drupal\Component\Utility\String;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uc_roles_help($path, RouteMatchInterface $route_match) {
  if ($path == 'node/%/edit/features/%/%' && $arg[4] == 'role') {
    return '<p>' . t('Add roles through this page and then use the <a href="!url">Rules interface</a> to limit which orders they are applied to. Most important is the order status on which role granting will be triggered.', array('!url' => \Drupal::url('admin/config/workflow/rules/reaction'))) . '</p>';
  }
  switch ($path) {
    case 'admin/people/expiration':
      return '<p>' . t('Ubercart grants certain roles to customers when they purchase products with a role assignment feature. These can be permanent or temporary roles. Here you can view and edit when temporary roles are set to expire.') . '</p>';
  }
}

/**
 * Implements hook_cron().
 */
function uc_roles_cron() {
  $reminder_granularity = variable_get('uc_roles_reminder_granularity', 'never');
  $reminder_qty = variable_get('uc_roles_reminder_length', NULL);

  $query = db_select('uc_roles_expirations', 'e')
    ->fields('e');
  $condition = db_or()
    ->condition('e.expiration', REQUEST_TIME, '<=');
  if ($reminder_granularity != 'never') {
    $condition->condition(db_and()
      ->isNull('e.notified')
      ->condition('e.expiration', _uc_roles_get_expiration($reminder_qty, $reminder_granularity, REQUEST_TIME), '<=')
    );
  }
  $query->condition($condition);

  $result = $query->execute();
  foreach ($result as $expiration) {
    $account = user_load($expiration->uid);

    // Cleanup if user or role was deleted already.
    if (!$account || !in_array($expiration->rid, array_keys($account->roles))) {
      uc_roles_delete($expiration, $expiration->rid, TRUE);
    }

    // Role expired.
    elseif ($expiration->expiration <= REQUEST_TIME) {
      // rules_invoke_event('uc_roles_notify_revoke', $account, $expiration);
      uc_roles_revoke($account, $expiration->rid);
    }

    // Remind the user about an upcoming expiration.
    elseif ($reminder_granularity != 'never') {
      // rules_invoke_event('uc_roles_notify_reminder', $account, $expiration);
      db_update('uc_roles_expirations')
        ->fields(array('notified' => 1))
        ->condition('uid', $account->id())
        ->condition('rid', $expiration->rid)
        ->execute();
    }
  }
}

/**
 * Implements hook_menu().
 */
function uc_roles_menu() {
  $items['admin/people/expiration'] = array(
    'title' => 'Role expiration',
    'description' => 'Edit and view role expirations set by Ubercart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_roles_expiration'),
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uc_roles.admin.inc',
  );
  $items['admin/people/expiration/delete/%user/%'] = array(
    'title' => 'Delete role expiration',
    'description' => 'Delete a specified role expiration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_roles_deletion_form', 4, 5),
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_roles.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function uc_roles_theme() {
  return array(
    'uc_roles_expiration' => array(
      'render element' => 'form',
      'file' => 'uc_roles.admin.inc',
      'function' => 'theme_uc_roles_expiration',
    ),
    'uc_roles_user_expiration' => array(
      'render element' => 'form',
      'file' => 'uc_roles.theme.inc',
      'function' => 'theme_uc_roles_user_expiration',
    ),
    'uc_roles_user_new' => array(
      'render element' => 'form',
      'file' => 'uc_roles.theme.inc',
      'function' => 'theme_uc_roles_user_new',
    ),
  );
}

/**
 * Implements hook_form_user_profile_form_alter().
 */
function uc_roles_form_user_profile_form_alter(&$form, FormStateInterface $form_state) {
  $account = $form_state->getFormObject()->getEntity();

  if (!\Drupal::currentUser()->hasPermission('administer users')) {
    return;
  }

  $role_choices = _uc_roles_get_choices(array_keys($account->roles));

  $polarity_widget = array(
    '#type' => 'select',
    '#options' => array(
      'add' => '+',
      'remove' => '-',
    ),
  );

  $quantity_widget = array(
    '#type' => 'textfield',
    '#size' => 4,
    '#maxlength' => 4
  );

  $granularity_widget = array(
    '#type' => 'select',
    '#options' => array(
      'day' => t('day(s)'),
      'week' => t('week(s)'),
      'month' => t('month(s)'),
      'year' => t('year(s)'),
    ),
  );

  $form['uc_roles'] = array(
    '#type' => 'details',
    '#title' => t('Ubercart roles'),
    '#weight' => 10,
    '#theme' => 'uc_roles_user_new',
  );

  $form['uc_roles']['expirations'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pending expirations'),
    '#weight' => 0,
    '#theme' => 'uc_roles_user_expiration',
  );

  $form['uc_roles']['expirations']['table']['#tree'] = TRUE;

  // Create the expirations table.
  $expirations = db_query("SELECT * FROM {uc_roles_expirations} WHERE uid = :uid", array(':uid' => $account->id()));
  foreach ($expirations as $expiration) {
    $form['uc_roles']['expirations']['table'][$expiration->rid] = array(
      'name' => array(
        '#type' => 'value',
        '#value' => _uc_roles_get_name($expiration->rid),
      ),
      'remove' => array(
        '#type' => 'checkbox',
      ),
      'expiration' => array(
        '#type' => 'value',
        '#value' => $expiration->expiration,
      ),
      'polarity' => $polarity_widget,
      'qty' => $quantity_widget,
      'granularity' => $granularity_widget,
    );
  }

  // Option to allow temporary roles.
  if (!empty($role_choices)) {
    $form['uc_roles']['new_role'] = array(
      '#type' => 'checkbox',
      '#title' => t('Add role'),
    );

    $form['uc_roles']['new_role_add'] = array(
      '#type' => 'select',
      '#default_value' => variable_get('uc_roles_default_role', NULL),
      '#options' => $role_choices,
    );

    $form['uc_roles']['new_role_add_for'] = array(
      '#markup' => ' ' . t('for') . ' ',
    );

    $form['uc_roles']['new_role_add_qty'] = $quantity_widget;
    $form['uc_roles']['new_role_add_granularity'] = $granularity_widget;

    if (($default_granularity = variable_get('uc_roles_default_granularity', 'never')) != 'never') {
      $form['uc_roles']['new_role_add_qty'] = $form['uc_roles']['new_role_add_qty'] + array('#default_value' => variable_get('uc_roles_default_length', NULL));
      $form['uc_roles']['new_role_add_granularity'] = $form['uc_roles']['new_role_add_granularity'] + array('#default_value' => $default_granularity);
    }
  }

  $form['#validate'][] = 'uc_roles_user_validate';

  return $form;
}

/**
 * User profile form validate handler.
 *
 * @see uc_roles_form_user_profile_form_alter()
 */
function uc_roles_user_validate($form, FormStateInterface $form_state) {
  $edit = $form_state->getValues();

  // Validate the amount of time for the expiration.
  if (!empty($edit['new_role'])) {
    if (intval($edit['new_role_add_qty']) < 1) {
      $form_state->setErrorByName('new_role_add_qty', t('The expiration length must be a positive integer'));
    }
  }

  // Validate adjusted expirations.
  if (isset($edit['table'])) {
    foreach ((array)$edit['table'] as $rid => $value) {
      // We don't validate if nothing was actually selected, the role, or the
      // expiration is removed.
      if ($value['qty'] == 0 || $value['remove'] == 1 || !$edit['roles'][$rid]) {
        continue;
      }

      $qty = $value['qty'];
      $qty *= $value['polarity'] == 'add' ? 1 : -1;

      $new_expiration = _uc_roles_get_expiration($qty, $value['granularity'], $value['expiration']);
      if (REQUEST_TIME > $new_expiration) {
        $form_state->setErrorByName('qty', t("The new expiration date, %date, has already occurred.", array('%date' => format_date($new_expiration, 'short'))));
      }
    }
  }
}

/**
 * Implements hook_user_cancel().
 */
function uc_roles_user_cancel($edit, $account, $method) {
  uc_roles_delete($account);
}

/**
 * Implements hook_user_presave().
 */
function uc_roles_user_presave($account) {
  if (!\Drupal::currentUser()->hasPermission('administer users')) {
    return;
  }

  // Grant a new role if a new temporary role is added.
  if (!empty($account->new_role)) {
    // Save our role info, but don't save the user; user.module will do that.
    uc_roles_grant($account, $account->new_role, _uc_roles_get_expiration($account->new_role_add_qty, $account->new_role_add_granularity), FALSE);

    // Push in values so user.module will save in the roles.
    $account->roles[$account->new_role_add] = _uc_roles_get_name($account->new_role_add);

    // Reset the new role form.
    unset($account->new_role);
    unset($account->new_role_add);
    unset($account->new_role_add_qty);
    unset($account->new_role_add_qty);
  }

  // Check if any temporary role actions were taken.
  if (isset($account->table)) {
    foreach ($account->table as $rid => $value) {
      // Remove this expiration.
      if ($value['remove']) {
        uc_roles_delete($account, $rid);
      }

      // Adjust it.
      else {
        if ($value['qty'] && $account->roles[$rid]) {
          $qty = $value['qty'];
          $qty *= $value['polarity'] == 'add' ? 1 : -1;

          uc_roles_renew($account, $rid, _uc_roles_get_expiration($qty, $value['granularity'], $value['expiration']));
        }
      }
    }
  }

  // If a user's role is removed using Drupal, then so is any expiration data.
  if (isset($account->original->roles)) {
    foreach ($account->original->roles as $rid => $role) {
      if (!in_array($rid, $account->roles) && $rid != DRUPAL_AUTHENTICATED_RID) {
        uc_roles_delete($account, $rid);
      }
    }
  }
}

/**
 * Implements hook_user_view().
 *
 * Displays role expirations on the user account screen.
 */
function uc_roles_user_view($account, $view_mode) {
  global $user;

  // Kick out anonymous or other view modes.
  if ($user->isAnonymous() || $view_mode != 'full') {
    return;
  }

  // Only show if this user can access all role expirations, or if it's the same
  // user and the expirations are showing on the user pages.
  $show_expiration = variable_get('uc_roles_default_show_expiration', TRUE);
  if (!$user->hasPermission('view all role expirations') && ($user->id() != $account->id() || !$show_expiration)) {
    return;
  }

  $form = array();
  $expirations = db_query("SELECT * FROM {uc_roles_expirations} WHERE uid = :uid", array(':uid' => $account->id()));
  foreach ($expirations as $expiration) {
    $form[$expiration->rid] = array(
      '#type' => 'item',
      '#title' => String::checkPlain(_uc_roles_get_name($expiration->rid)),
      '#markup' => t('This role will expire on !date', array('!date' => format_date($expiration->expiration, 'short'))),
    );
  }

  // Don't display anything if there aren't any expirations.
  if (!count($form)) {
    return;
  }

  $item = array(
    '#type' => 'item',
    '#weight' => '-1',
    '#title' => t('Expiring roles'),
  );

  $account->content['uc_roles'] = $item + $form;
}

/**
 * Implements hook_uc_order_product_can_ship().
 */
function uc_roles_uc_order_product_can_ship($item) {
  $roles = db_query("SELECT * FROM {uc_roles_products} WHERE nid = :nid", array(':nid' => $item->nid->target_id));
  foreach ($roles as $role) {
    // If the model is empty, keep looking. (Everyone needs a role model...)
    if (empty($role->model)) {
      continue;
    }

    // If there's an adjusted SKU, use it... otherwise use the node SKU.
    $sku = (empty($item->data['model'])) ? $item->model->value : $item->data['model'];

    // Keep looking if it doesn't match.
    if ($sku != $role->model) {
      continue;
    }

    return $role->shippable;
  }
}

/**
 * Implements hook_uc_product_feature().
 */
function uc_roles_uc_product_feature() {
  $features[] = array(
    'id' => 'role',
    'title' => t('Role assignment'),
    'callback' => 'Drupal\uc_roles\Form\RoleFeatureForm',
    'delete' => 'uc_roles_feature_delete',
    'settings' => 'uc_roles_feature_settings',
  );

  return $features;
}

/**
 * Implements hook_uc_store_status().
 */
function uc_roles_uc_store_status() {
  $message = array();
  $role_choices = _uc_roles_get_choices();
  if (empty($role_choices)) {
    $message[] = array(
      'status' => 'warning',
      'title' => t('Roles'),
      'desc' => t('There are no product role(s) that can be assigned upon product purchase. Set product roles in the <a href="!url">product settings</a> under the role assignment settings tab.', array('!url' => \Drupal::url('uc_product.settings'))),
    );
  }
  else {
    $message[] = array(
      'status' => 'ok',
      'title' => t('Roles'),
      'desc' => t('The role(s) %roles are set to be used with the Role Assignment product feature.', array('%roles' => implode(', ', $role_choices))),
    );
  }
  return $message;
}

/**
 * Form builder for role settings.
 *
 * @see uc_roles_feature_settings_submit()
 * @ingroup forms
 */
function uc_roles_feature_settings($form, FormStateInterface $form_state) {
  $default_role_choices = user_role_names(TRUE);
  unset($default_role_choices[DRUPAL_AUTHENTICATED_RID]);

  if (!count($default_role_choices)) {
    $form['no_roles'] = array(
      '#markup' => t('You need to <a href="!url">create new roles</a> before any can be added as product features.', array('!url' => \Drupal::url('user.role_add', [], ['query' => ['destination' => 'admin/store/settings/products']]))),
      '#prefix' => '<p>',
      '#suffix' => '</p>',
    );

    return $form;
  }

  $form['uc_roles_default_role'] = array(
    '#type' => 'select',
    '#title' => t('Default role'),
    '#default_value' => variable_get('uc_roles_default_role', NULL),
    '#description' => t('The default role Ubercart grants on specified products.'),
    '#options' => _uc_roles_get_choices(),
  );
  $form['uc_roles_default_role_choices'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Product roles'),
    '#default_value' => variable_get('uc_roles_default_role_choices', array()),
    '#multiple' => TRUE,
    '#description' => t('These are roles that Ubercart can grant to customers who purchase specified products. If you leave all roles unchecked, they will all be eligible for adding to a product.'),
    '#options' => $default_role_choices,
  );

  $form['role_lifetime'] = array(
    '#type' => 'fieldset',
    '#title' => t('Default role expiration'),
  );

  $form['role_lifetime']['uc_roles_default_end_expiration'] = array(
    '#type' => 'select',
    '#title' => t('Expiration type'),
    '#options' => array(
      'rel' => t('Relative to purchase date'),
      'abs' => t('Fixed date'),
    ),
    '#default_value' => variable_get('uc_roles_default_end_expiration', 'rel'),
  );
  $form['role_lifetime']['uc_roles_default_length'] = array(
    '#type' => 'textfield',
    '#default_value' => (variable_get('uc_roles_default_granularity', 'never') == 'never') ? NULL : variable_get('uc_roles_default_length', NULL),
    '#size' => 4,
    '#maxlength' => 4,
    '#prefix' => '<div class="expiration">',
    '#suffix' => '</div>',
    '#states' => array(
      'visible' => array('select[name="uc_roles_default_end_expiration"]' => array('value' => 'rel')),
      'invisible' => array('select[name="uc_roles_default_granularity"]' => array('value' => 'never')),
    ),
  );
  $form['role_lifetime']['uc_roles_default_granularity'] = array(
    '#type' => 'select',
    '#default_value' => variable_get('uc_roles_default_granularity', 'never'),
    '#options' => array(
      'never' => t('never'),
      'day' => t('day(s)'),
      'week' => t('week(s)'),
      'month' => t('month(s)'),
      'year' => t('year(s)')
    ),
    '#description' => t('From the time the role was purchased.'),
    '#prefix' => '<div class="expiration">',
    '#suffix' => '</div>',
    '#states' => array(
      'visible' => array('select[name="uc_roles_default_end_expiration"]' => array('value' => 'rel')),
    ),
  );
  $form['role_lifetime']['absolute'] = array(
    '#type' => 'container',
    '#states' => array(
      'visible' => array('select[name="uc_roles_default_end_expiration"]' => array('value' => 'abs')),
    ),
  );
  $form['role_lifetime']['absolute']['uc_roles_default_end_time'] = array(
    '#type' => 'date',
    '#description' => t('Expire the role at the beginning of this day.'),
    '#default_value' => variable_get('uc_roles_default_end_time', array(
      'day' => date('j'),
      'month' => date('n'),
      'year' => date('Y'),
    )),
  );
  $form['role_lifetime']['uc_roles_default_by_quantity'] = array(
    '#type' => 'checkbox',
    '#title' => t('Multiply by quantity'),
    '#description' => t('Check if the role duration should be multiplied by the quantity purchased.'),
    '#default_value' => variable_get('uc_roles_default_by_quantity', FALSE),
  );
  $form['reminder']['uc_roles_reminder_length'] = array(
    '#type' => 'textfield',
    '#title' => t('Time before reminder'),
    '#default_value' => (variable_get('uc_roles_reminder_granularity', 'never') == 'never') ? NULL : variable_get('uc_roles_reminder_length', NULL),
    '#size' => 4,
    '#maxlength' => 4,
    '#prefix' => '<div class="expiration">',
    '#suffix' => '</div>',
    '#states' => array(
      'disabled' => array('select[name="uc_roles_reminder_granularity"]' => array('value' => 'never')),
    ),
  );
  $form['reminder']['uc_roles_reminder_granularity'] = array(
    '#type' => 'select',
    '#default_value' => variable_get('uc_roles_reminder_granularity', 'never'),
    '#options' => array(
      'never' => t('never'),
      'day' => t('day(s)'),
      'week' => t('week(s)'),
      'month' => t('month(s)'),
      'year' => t('year(s)')
    ),
    '#description' => t('The amount of time before a role expiration takes place that a customer is notified of its expiration.'),
    '#prefix' => '<div class="expiration">',
    '#suffix' => '</div>',
  );
  $form['uc_roles_default_show_expiration'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show expirations on user page'),
    '#default_value' => variable_get('uc_roles_default_show_expiration', TRUE),
    '#description' => t('If users have any role expirations they will be displayed on their account page.'),
  );
  return $form;
}

/**
 * Form submission handler for uc_roles_feature_settings().
 *
 * @see uc_roles_feature_settings()
 */
function uc_roles_feature_settings_submit($form, FormStateInterface $form_state) {
  variable_set('uc_roles_default_role', $form_state->getValue('uc_roles_default_role'));
  variable_set('uc_roles_default_role_choices', $form_state->getValue('uc_roles_default_role_choices'));
  variable_set('uc_roles_default_end_expiration', $form_state->getValue('uc_roles_default_end_expiration'));
  variable_set('uc_roles_default_length', $form_state->getValue('uc_roles_default_length'));
  variable_set('uc_roles_default_granularity', $form_state->getValue('uc_roles_default_granularity'));
  variable_set('uc_roles_default_end_time', $form_state->getValue('uc_roles_default_end_time'));
  variable_set('uc_roles_default_by_quantity', $form_state->getValue('uc_roles_default_by_quantity'));
  variable_set('uc_roles_reminder_length', $form_state->getValue('uc_roles_reminder_length'));
  variable_set('uc_roles_reminder_granularity', $form_state->getValue('uc_roles_reminder_granularity'));
  variable_set('uc_roles_default_show_expiration', $form_state->getValue('uc_roles_default_show_expiration'));
  variable_set('uc_roles_default_expiration_header', $form_state->getValue('uc_roles_default_expiration_header'));
  variable_set('uc_roles_default_expiration_title', $form_state->getValue('uc_roles_default_expiration_title'));
  variable_set('uc_roles_default_expiration_message', $form_state->getValue('uc_roles_default_expiration_message'));
}

/**
 * Gets role name.
 *
 * @param $rid
 *   The Drupal role id number.
 *
 * @return
 *   A string containing the name of the role, returns FALSE if rid is invalid.
 */
function _uc_roles_get_name($rid) {
  $roles = user_role_names(TRUE);
  return (!is_null($roles[$rid])) ? $roles[$rid] : FALSE;
}

/**
 * Gets available roles for granting on product purchase.
 *
 * @param $exclude
 *   A list of role ids to exclude from the list.
 *
 * @return
 *   An assoc array with key = rid and value = role name.
 */
function _uc_roles_get_choices($exclude = array()) {
  $output = array();

  // Get roles from Drupal, excluding Anonymous and Authenticated.
  $roles = user_role_names(TRUE);
  unset($roles[DRUPAL_AUTHENTICATED_RID]);

  // User set specific roles that we must use?
  $selected = variable_get('uc_roles_default_role_choices', array());

  // If there's none, or if none are checked, use all of em.
  $default = empty($selected) || array_sum($selected) == 0;
  foreach ($roles as $rid => $name) {
    if ($default || (!empty($selected[$rid]) && !in_array($rid, $exclude))) {
      $output[$rid] = $roles[$rid];
    }
  }

  return $output;
}

/**
 * Deletes all data associated with a given product feature.
 *
 * @param $pfid
 *   An Ubercart product feature ID.
 */
function uc_roles_feature_delete($pfid) {
  db_delete('uc_roles_products')
    ->condition('pfid', $pfid)
    ->execute();
}

/**
 * Deletes an expiration using user id or user id and rid.
 *
 * This function deletes expirations associated with users and roles. If
 * no role ID is passed, the function deletes all role expirations associated
 * with the given user. Otherwise, the function only deletes expirations whose
 * user and role IDs match. If any roles were actually deleted, the function
 * notifies the user. The menu cache is then flushed, as privileges to view
 * menu items may have been lost in the process.
 *
 * @param $account
 *   A Drupal user object.
 * @param $rid
 *   A Drupal role ID.
 * @param $silent
 *   When set to TRUE will suppress any Drupal messages from this function.
 */
function uc_roles_delete($account, $rid = NULL, $silent = FALSE) {
  global $user;

  $query = db_delete('uc_roles_expirations')
    ->condition('uid', $account->id());

  if ($rid) {
    $query->condition('rid', $rid);
  }

  // Echo the deletion only if something was actually deleted.
  if ($query->execute() && !$silent) {
    if ($user->id() == $account->id()) {
      drupal_set_message(t('The expiration of your %role_name role has been deleted.', array('%role_name' => _uc_roles_get_name($rid))));
    }
    else {
      drupal_set_message(t('The expiration of %role_name role for the user !user has been deleted.', array(
        '!user' => theme('username', array(
          'account' => $account,
          'name' => String::checkPlain(user_format_name($account)),
          'link_path' => 'user/' . $account->id(),
        )),
        '%role_name' => _uc_roles_get_name($rid),
      )));
    }
  }

  // Flush visible menu items, since our permissions could've changed.
  _uc_roles_flush_menu_cache($account);
}

/**
 * Revokes a role on a given user
 *
 * This function deletes a given role from a user's list of roles, as
 * well as removing any expiration data associated with the user/role.
 * The function notifies the user of revocation.
 *
 * @param $account
 *   A Drupal user object.
 * @param $rid
 *   A Drupal role ID.
 * @param $silent
 *   When set to TRUE will suppress any Drupal messages from this function.
 */
function uc_roles_revoke(&$account, $rid, $silent = FALSE) {
  global $user;

  // Remove this role from the user's list.
  unset($account->roles[$rid]);
  $account->save();

  // Remove our record of the expiration.
  uc_roles_delete($account, $rid, $silent);

  $role_name = db_query("SELECT name FROM {role} WHERE rid = :rid", array(':rid' => $rid))->fetchField();

  if (!$silent) {
    if ($user->id() == $account->id()) {
      drupal_set_message(t('Your %role role has been revoked.', array('%role' => $role_name)));
    }
    else {
      drupal_set_message(t('!user has had the %role role revoked.', array(
        '!user' => theme('username', array(
          'account' => $account,
          'name' => String::checkPlain(user_format_name($account)),
          'link_path' => 'user/' . $account->id(),
        )),
        '%role' => $role_name,
      )));
    }
  }
}

/**
 * Grants a role to a given user
 *
 * This function grants a given role to a user's list of roles. If there
 * is a previous record of this user/role combination, it is first removed.
 * The function then saves the user (if $user_save is TRUE). Next, a check
 * to verify the role actually exists, if not, no expiration data is stored.
 * The menu cache is flushed, as new menu items may be visible after the
 * new role is granted. The function notifies the user of the role grant.
 *
 * @param $account
 *   A Drupal user object.
 * @param $rid
 *   A Drupal role ID.
 * @param $timestamp
 *   When this role will expire.
 * @param $save_user
 *   Optimization to prevent unnecessary user saving when calling from
 *   uc_roles_user_presave().
 * @param $silent
 *   When set to TRUE will suppress any Drupal messages from this function.
 */
function uc_roles_grant(&$account, $rid, $timestamp, $save_user = TRUE, $silent = FALSE) {
  global $user;

  // First, delete any previous record of this user/role association.
  uc_roles_delete($account, $rid, $silent);

  if ($save_user) {
    // Punch the role into the user object.
    $account->roles += array($rid => _uc_roles_get_name($rid));
    $account->save();
  }


  // If the role expires, keep a record.
  if (!is_null($timestamp)) {
    db_insert('uc_roles_expirations')
      ->fields(array(
        'uid' => $account->id(),
        'rid' => $rid,
        'expiration' => $timestamp,
      ))
      ->execute();
  }

  // Flush visible menu items, since our permissions could've changed.
  _uc_roles_flush_menu_cache($account);

  // Display the message if appropriate.
  if (!$silent) {
    $role_name = db_query("SELECT name FROM {role} WHERE rid = :rid", array(':rid' => $rid))->fetchField();

    if ($user->id() == $account->id()) {
      $message = t('You have been granted the %role role.', array('%role' => $role_name));
    }
    else {
      $message = t('!user has been granted the %role role.', array(
        '!user' => theme('username', array(
          'account' => $account,
          'name' => String::checkPlain(user_format_name($account)),
          'link_path' => 'user/' . $account->id(),
        )),
        '%role' => $role_name,
      ));
    }

    if ($timestamp) {
      $message .= ' ' . t('It will expire on %date', array('%date' => format_date($timestamp, 'short')));
    }

    drupal_set_message($message);
  }
}

/**
 * Renews a given role on a user.
 *
 * This function updates expiration time on a role already granted to a
 * user. First the function checks the new expiration. If it never expires,
 * the function deletes the past expiration record and returns, leaving
 * management up to Drupal. Otherwise, the record is updated with the new
 * expiration time, and the user is notified of the change.
 *
 * @param $account
 *   A Drupal user object.
 * @param $rid
 *   A Drupal role ID.
 * @param $timestamp
 *   When this role will expire.
 * @param $silent
 *   When set to TRUE will suppress any Drupal messages from this function.
 */
function uc_roles_renew($account, $rid, $timestamp, $silent = FALSE) {
  global $user;

  // If it doesn't expire, we'll remove our data associated with it.
  // After that, Drupal will take care of it.
  if (is_null($timestamp)) {
    uc_roles_delete($account, $rid);

    return;
  }

  // Update the expiration date and reset the notified flag.
  db_update('uc_roles_expirations')
    ->fields(array(
      'expiration' => $timestamp,
      'notified' => NULL,
    ))
    ->condition('uid', $account->id())
    ->condition('rid', $rid)
    ->execute();

  if (!$silent) {
    $role_name = db_query("SELECT name FROM {role} WHERE rid = :rid", array(':rid' => $rid))->fetchField();
    if ($user->id() == $account->id()) {
      $message = t('Your %role role has been renewed. It will expire on %date.', array('%role' => $role_name, '%date' => format_date($timestamp, 'short')));
    }
    else {
      $message = t("!user's %role role has been renewed. It will expire on %date.", array(
        '!user' => theme('username', array(
          'account' => $account,
          'name' => String::checkPlain(user_format_name($account)),
          'link_path' => 'user/' . $account->id(),
        )),
        '%role' => $role_name,
        '%date' => format_date($timestamp, 'short'),
      ));
    }

    drupal_set_message($message);
  }
}

/**
 * Flushes the menu cache.
 *
 * When roles are gained/lost, menu items might appear/disappear respectively,
 * so we have to ensure the cache is rebuilt with any new values.
 *
 * @param $account
 *   A Drupal user object.
 *
 * @see uc_roles_delete()
 * @see uc_roles_grant()
 */
function _uc_roles_flush_menu_cache($account) {
  cache_clear_all($account->id() . ':', 'cache_menu', TRUE);
}

/**
 * Calculates the expiration time using a role_product object.
 *
 * @param $role_product
 *   The role product object whose expiration times to calculate.
 * @param $quantity
 *   Used to multiply any relative expiration time, if the $role_product
 *   says to.
 * @param $time
 *   The current time to use as a starting point for relative expiration
 *   calculation.
 */
function _uc_roles_product_get_expiration($role_product, $quantity, $time) {
  // Override the end expiration?
  if ($role_product->end_override) {

    // Absolute times are easy...
    if ($role_product->end_time) {
      return $role_product->end_time;
    }

    // We're gonna have to calculate the relative time from $time.
    $length = $role_product->duration * ($role_product->by_quantity ? $quantity : 1);
    return _uc_roles_get_expiration($length, $role_product->granularity, $time);
  }

  // No override, use the default expiration values.
  else {
    // Relative...
    if (variable_get('uc_roles_default_end_expiration', 'rel') === 'rel') {
      $length = variable_get('uc_roles_default_length', NULL) * ($role_product->by_quantity ? $quantity : 1);
      return _uc_roles_get_expiration($length, variable_get('uc_roles_default_granularity', 'never'), $time);
    }

    // Absolute...
    $end_time = variable_get('uc_roles_default_end_time', NULL);
    if ($end_time) {
      $end_time = mktime(0, 0, 0, $end_time['month'], $end_time['day'], $end_time['year']);
    }

    return $end_time;
  }
}

/**
 * Returns an expiration time stamp given a period of time.
 *
 * @param $duration
 *   The amount of time until expiration.
 * @param $granularity
 *   A string representing the granularity's name (e.g. "day", "month", etc.).
 * @param $start_time
 *   (optional) The starting date for when the role will last. Defaults to
 *   the current time.
 *
 * @return
 *   A UNIX timestamp representing the second that expiration takes place,
 *   or NULL if the expiration should never occur.
 */
function _uc_roles_get_expiration($duration, $granularity, $start_time = NULL) {
  // Never expires?
  if ($granularity == 'never') {
    return NULL;
  }

  $start_time = (!is_null($start_time)) ? $start_time : REQUEST_TIME;
  $operator = ($duration < 0) ? '' : '+';

  return strtotime($operator . $duration . ' ' . $granularity, $start_time);
}
