<?php

/**
 * @file
 * Provides the Check/Money Order, COD, and "Other" payment methods.
 */


/**
 * Implements hook_menu().
 */
function uc_payment_pack_menu() {
  $items['admin/store/orders/%uc_order/receive_check'] = array(
    'title' => 'Receive check',
    'description' => 'Record details of a check that has been received.',
    'route_name' => 'uc_payment_pack.check.receive',
  );

  return $items;
}

/**
 * Implements hook_uc_payment_method().
 */
function uc_payment_pack_uc_payment_method() {
  $methods['check'] = array(
    'name'       => t('Check', array(), array('context' => 'cheque')),
    'title'      => t('Check or money order'),
    'desc'       => t('Pay by mailing a check or money order.'),
    'callback'   => 'uc_payment_method_check',
    'weight'     => 1,
    'checkout'   => TRUE,
    'no_gateway' => TRUE,
  );
  $methods['cod'] = array(
    'name'       => t('COD'),
    'title'      => t('Cash on delivery'),
    'desc'       => t('Pay cash on delivery on pick-up.'),
    'callback'   => 'uc_payment_method_cod',
    'weight'     => 1,
    'checkout'   => FALSE,
    'no_gateway' => TRUE,
  );
  $methods['other'] = array(
    'name'       => t('Other'),
    'title'      => t('Other'),
    'desc'       => t('A generic payment method type.'),
    'callback'   => 'uc_payment_method_other',
    'weight'     => 10,
    'checkout'   => FALSE,
    'no_gateway' => TRUE,
  );

  return $methods;
}

/**
 * Payment method callback for the generic payment method "Other".
 */
function uc_payment_method_other($op, &$order) {
  switch ($op) {
    case 'order-view':
    case 'customer-view':
      // Fetch the description for the payment entered by the administrator.
      if ($description = db_query('SELECT description FROM {uc_payment_other} WHERE order_id = :id', array(':id' => $order->id()))->fetchField()) {
        return array('#markup' => t('Description: @desc', array('@desc' => $description)));
      }
      break;

    case 'order-details':
      $form['pm_other_description'] = array(
        '#type' => 'textfield',
        '#title' => t('Description'),
        '#default_value' => isset($order->payment_details['description']) ? $order->payment_details['description'] : '',
        '#size' => 32,
        '#maxlength' => 64,
      );
      return $form;

    case 'order-load':
      $description = db_query('SELECT description FROM {uc_payment_other} WHERE order_id = :id', array(':id' => $order->id()))->fetchField();
      if (isset($description)) {
        $order->payment_details['description'] = $description;
      }
      break;

    case 'order-save':
      if (empty($order->payment_details['pm_other_description'])) {
        db_delete('uc_payment_other')
          ->condition('order_id', $order->id())
          ->execute();
      }
      else {
        db_merge('uc_payment_other')
          ->key(array(
            'order_id' => $order->id(),
          ))
          ->fields(array(
            'description' => $order->payment_details['pm_other_description'],
          ))
          ->execute();
      }
      break;
  }
}

/**
 * Payment method callback for the "Cash on Delivery" payment method.
 */
function uc_payment_method_cod($op, &$order, $form = NULL, $form_state = NULL) {
  $cod_config = \Drupal::config('uc_cod.settings');
  switch ($op) {
    case 'cart-details':
      $build['policy'] = array(
        '#markup' => '<p>' . $cod_config->get('policy') . '</p>'
      );

      if (($max = $cod_config->get('max_order')) > 0 && is_numeric($max)) {
        $build['eligibility'] = array(
          '#markup' => '<p>' . t('Orders totalling more than !number are <b>not eligible</b> for COD.', array('!number' => uc_currency_format($max))) . '</p>'
        );
      }

      if ($cod_config->get('delivery_date')) {
        $build += uc_payment_method_cod_form(array(), $form_state, $order);
      }
      return $build;

    case 'cart-process':
      if ($cod_config->get('delivery_date')) {
        $order->payment_details = $form_state['values']['panes']['payment']['details'];
      }
      return TRUE;

    case 'cart-review':
      $review = array();
      if ($cod_config->get('delivery_date')) {
        $date = uc_date_format(
          $order->payment_details['delivery_month'],
          $order->payment_details['delivery_day'],
          $order->payment_details['delivery_year']
        );
        $review[] = array('title' => t('Delivery date'), 'data' => $date);
      }
      return $review;

    case 'order-view':
    case 'customer-view':
      $build = array('#markup' => '');
      if ($cod_config->get('delivery_date') &&
          isset($order->payment_details['delivery_month']) &&
          isset($order->payment_details['delivery_day']) &&
          isset($order->payment_details['delivery_year'])) {
        $build['#markup'] = t('Desired delivery date:') . '<br />' .
          uc_date_format(
            $order->payment_details['delivery_month'],
            $order->payment_details['delivery_day'],
            $order->payment_details['delivery_year']
          );
      }
      return $build;

    case 'order-details':
      $build = array();
      if ($cod_config->get('delivery_date')) {
        $build = uc_payment_method_cod_form(array(), $form_state, $order);
      }
      return $build;

    case 'order-load':
      $result = db_query('SELECT * FROM {uc_payment_cod} WHERE order_id = :id', array(':id' => $order->id()));
      if ($row = $result->fetchObject()) {
        $order->payment_details = array(
          'delivery_month' => $row->delivery_month,
          'delivery_day'   => $row->delivery_day,
          'delivery_year'  => $row->delivery_year,
        );
      }
      break;

    case 'order-submit':
      if ($order->getPaymentMethodId() == 'cod' &&
          ($max = $cod_config->get('max_order')) > 0 &&
          is_numeric($max) &&
          $order->getTotal() > $max) {
        $result[] = array(
          'pass' => FALSE,
          'message' => t('Your final order total exceeds the maximum for COD payment.  Please go back and select a different method of payment.')
        );
        return $result;
      }
      // TODO: This falls through to the order-save case - is this deliberate?
      // If so, it should be documented.

    case 'order-save':
      if (isset($order->payment_details['delivery_month']) &&
          isset($order->payment_details['delivery_day'])   &&
          isset($order->payment_details['delivery_year'])    ) {
        db_merge('uc_payment_cod')
          ->key(array('order_id' => $order->id()))
          ->fields(array(
            'delivery_month' => $order->payment_details['delivery_month'],
            'delivery_day'   => $order->payment_details['delivery_day'],
            'delivery_year'  => $order->payment_details['delivery_year'],
          ))
          ->execute();
      }
      break;

    case 'order-delete':
      db_delete('uc_payment_cod')
        ->condition('order_id', $order->id())
        ->execute();
      break;

    case 'settings':
      $form['uc_cod_policy'] = array(
        '#type' => 'textarea',
        '#title' => t('Policy message'),
        '#default_value' => $cod_config->get('policy'),
        '#description' => t('Help message shown at checkout.'),
      );
      $form['uc_cod_max_order'] = array(
        '#type' => 'textfield',
        '#title' => t('Maximum order total eligible for COD'),
        '#default_value' => $cod_config->get('max_order'),
        '#description' => t('Set to 0 for no maximum order limit.'),
      );
      $form['uc_cod_delivery_date'] = array(
        '#type' => 'checkbox',
        '#title' => t('Let customers enter a desired delivery date.'),
        '#default_value' => $cod_config->get('delivery_date'),
      );
      return $form;
  }
}

/**
 * Collect additional information for the "Cash on Delivery" payment method.
 *
 * @ingroup forms
 */
function uc_payment_method_cod_form($form, &$form_state, $order) {
  $month = !empty($order->payment_details['delivery_month']) ? $order->payment_details['delivery_month'] : format_date(REQUEST_TIME, 'custom', 'n');
  $day   = !empty($order->payment_details['delivery_day'])   ? $order->payment_details['delivery_day']   : format_date(REQUEST_TIME, 'custom', 'j');
  $year  = !empty($order->payment_details['delivery_year'])  ? $order->payment_details['delivery_year']  : format_date(REQUEST_TIME, 'custom', 'Y');

  $form['description'] = array(
    '#markup' => '<div>' . t('Enter a desired delivery date:') . '</div>',
  );
  $form['delivery_month'] = uc_select_month(NULL, $month);
  $form['delivery_day']   = uc_select_day(NULL, $day);
  $form['delivery_year']  = uc_select_year(NULL, $year, format_date(REQUEST_TIME, 'custom', 'Y'), format_date(REQUEST_TIME, 'custom', 'Y') + 1);

  return $form;
}

/**
 * Payment method callback for the "Check" payment method.
 */
function uc_payment_method_check($op, &$order, $form = NULL, &$form_state = NULL) {
  $check_config = \Drupal::config('uc_check.settings');
  switch ($op) {
    case 'cart-details':
      $build['instructions'] = array(
        '#markup' => t('Checks should be made out to:')
      );

      if (!$check_config->get('mailing_street1')) {
        $build['address'] = array(
          '#markup' => uc_store_address(),
          '#prefix' => '<p>',
          '#suffix' => '</p>',
        );
      }
      else {
        $build['address'] = array(
          '#markup' => uc_address_format(
            $check_config->get('mailing_name'),
            NULL,
            $check_config->get('mailing_company'),
            $check_config->get('mailing_street1'),
            $check_config->get('mailing_street2'),
            $check_config->get('mailing_city'),
            $check_config->get('mailing_zone'),
            $check_config->get('mailing_postal_code'),
            $check_config->get('mailing_country')
          ),
          '#prefix' => '<p>',
          '#suffix' => '</p>',
        );
      }

      $build['policy'] = array(
        '#markup' => '<p>' . $check_config->get('policy') . '</p>'
      );
      return $build;

    case 'cart-review':
      if (!$check_config->get('mailing_street1')) {
        $review[] = array(
          'title' => t('Mail to'),
          'data' => uc_store_address(),
        );
      }
      else {
        $review[] = array(
          'title' => t('Mail to'),
          'data' => uc_address_format(
            $check_config->get('mailing_name'),
            NULL,
            $check_config->get('mailing_company'),
            $check_config->get('mailing_street1'),
            $check_config->get('mailing_street2'),
            $check_config->get('mailing_city'),
            $check_config->get('mailing_zone'),
            $check_config->get('mailing_postal_code'),
            $check_config->get('mailing_country')
          )
        );
      }
      return $review;

    case 'order-view':
      $build = array('#suffix' => '<br />');

      $result = db_query('SELECT clear_date FROM {uc_payment_check} WHERE order_id = :id ', array(':id' => $order->id()));
      if ($clear_date = $result->fetchField()) {
        $build['#markup'] = t('Clear Date:') . ' ' . format_date($clear_date, 'uc_store');
      }
      else {
        $build['#markup'] = l(t('Receive Check'), 'admin/store/orders/' . $order->id() . '/receive_check');
      }
      return $build;

    case 'customer-view':
      $build = array();
      $result = db_query('SELECT clear_date FROM {uc_payment_check} WHERE order_id = :id ', array(':id' => $order->id()));
      if ($clear_date = $result->fetchField()) {
        $build['#markup'] = t('Check received') . '<br />' .
          t('Expected clear date:') . '<br />' . format_date($clear_date, 'uc_store');
      }
      return $build;

    case 'settings':
      $form['check_address_info'] = array(
        '#markup' => '<div>' . t('Set the mailing address to display to customers who choose this payment method during checkout.') . '</div>',
      );
      $form['uc_check_mailing_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Contact'),
        '#description' => t('Direct checks to a person or department.'),
        '#default_value' => $check_config->get('mailing_name'),
      );
      $form['uc_check_address'] = array(
        '#type' => 'uc_address',
        '#default_value' => array(
          'uc_check_mailing_company' => $check_config->get('mailing_company'),
          'uc_check_mailing_street1' => $check_config->get('mailing_street1'),
          'uc_check_mailing_street2' => $check_config->get('mailing_street2'),
          'uc_check_mailing_city' => $check_config->get('mailing_city'),
          'uc_check_mailing_zone' => $check_config->get('mailing_zone'),
          'uc_check_mailing_country' => isset($form_state['values']['uc_check_mailing_country']) ? $form_state['values']['uc_check_mailing_country'] : $check_config->get('uc_check_mailing_country'),
          'uc_check_mailing_postal_code' => $check_config->get('mailing_postal_code'),
        ),
        '#required' => FALSE,
        '#key_prefix' => 'uc_check_mailing',
      );
      $form['uc_check_policy'] = array(
        '#type' => 'textarea',
        '#title' => t('Check payment policy', array(), array('context' => 'cheque')),
        '#description' => t('Instructions for customers on the checkout page.'),
        '#default_value' => $check_config->get('policy'),
        '#rows' => 3,
      );
      return $form;
  }
}
