<?php

/**
 * @file
 * Integrates various PayPal payment services and IPN with Ubercart.
 *
 * You should turn on Instant Payment Notifications in your PayPal profile and
 * set the IPN URL to http://{yoursite.com}/uc_paypal/ipn. See
 * https://drupal.org/node/1311198 for further information.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function uc_paypal_help($route_name, RouteMatchInterface $route_match) {
  // @todo: write better help!
  // Provide information and instructions on the payment method add form.
  if ($route_name == 'entity.uc_payment_method.add_form') {
    if ($route_match->getRawParameter('plugin_id') == 'paypal_ec') {
      return '<p>' . t('PayPal Express Checkout settings help.') . '</p>';
    }
    elseif ($route_match->getRawParameter('plugin_id') == 'paypal_wps') {
      return '<p>' . t('PayPal Payments Standard settings help.') . '</p>';
    }
  }
  // Provide information and instructions on the payment method edit form.
  elseif ($route_name == 'entity.uc_payment_method.edit_form') {
    if ($route_match->getParameter('uc_payment_method')->getPlugin()->getPluginId() == 'paypal_ec') {
      return '<p>' . t('PayPal Express Checkout settings help.') . '</p>';
    }
    elseif ($route_match->getParameter('uc_payment_method')->getPlugin()->getPluginId() == 'paypal_wps') {
      return '<p>' . t('PayPal Payments Standard settings help.') . '</p>';
    }
  }
}

/**
 * Implements hook_uc_payment_gateway().
 */
function uc_paypal_uc_payment_gateway() {
  if (!\Drupal::moduleHandler()->moduleExists('uc_credit')) {
    drupal_set_message(t('You must <a href=":modules">enable the Credit Card module</a> to use PayPal Website Payments Pro.', [':modules' => Url::fromRoute('system.modules_list', [], ['fragment' => 'edit-modules-ubercart-payment'])->toString()]), 'warning');
    return;
  }

  $gateways['paypal_wpp'] = array(
    'title' => t('PayPal Website Payments Pro'),
    'description' => t('Process credit card payments using Website Payments Pro.'),
    'settings' => 'uc_paypal_wpp_settings_form',
    'credit' => 'uc_paypal_wpp_charge',
    'credit_txn_types' => array(UC_CREDIT_AUTH_ONLY, UC_CREDIT_PRIOR_AUTH_CAPTURE, UC_CREDIT_AUTH_CAPTURE),
  );

  return $gateways;
}

  // Payment method titles ...
  //
  // $title1 = '<img src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif" alt="PayPal" class="uc-credit-cctype" />'
  //       . ' ' . t('PayPal - pay without sharing your financial information.');
  /*
  $title2 = '<br /><span id="paypal-includes">' . t('Includes:');
  $cc_types = array(
    'visa' => t('Visa'),
    'mastercard' => t('MasterCard'),
    'discover' => t('Discover'),
    'amex' => t('American Express'),
    'echeck' => t('eCheck'),
  );
  foreach ($cc_types as $type => $label) {
    $title2 .= ' ' . theme('image', array(
      'uri' => drupal_get_path('module', 'uc_credit') . '/images/' . $type . '.gif',
      'alt' => $label,
      'attributes' => array('class' => array('uc-credit-cctype', 'uc-credit-cctype-' . $type)),
    ));
  }
  $title2 .= ' <img src="https://www.paypal.com/en_US/i/logo/PayPal_mark_37x23.gif" alt="PayPal" class="uc-credit-cctype" /></span>';
  */
