<?php

/**
 * @file
 * Handles all things concerning Ubercart orders.
 *
 * The order system allows for backend order creation, editing, and management.
 * Hooks allow for third party module integration, automated fulfillment, and
 * more.  This module also governs the order review options and invoices
 * displayed to customers.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Language\Language;
use Drupal\Core\Template\Attribute;

require_once dirname(__FILE__) . '/uc_order.order_pane.inc';
require_once dirname(__FILE__) . '/uc_order.line_item.inc';


/**
 * Implements hook_help().
 */
function uc_order_help($path, $arg) {
  switch ($path) {
    case 'admin/store/settings/orders/products/fields':
      return '<p>' . t('Attach fields to order product entities.  These entities represent the product line items that appear in orders.  Fields attached here are not visible in the current version of Ubercart, but they are available in Views.  A ')
        . l(t('Computed Field'), 'http://drupal.org/project/computed_field')
        . t(' is useful for attaching custom data to each product as it is ordered.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function uc_order_menu() {
  $items['admin/store/customers'] = array(
    'title' => 'Customers',
    'description' => 'View and search customer information.',
    'route_name' => 'uc_order.customer_admin',
    'weight' => -6,
    'position' => 'left',
  );
  // admin/store/customers/view is provided by Views.
  // admin/store/customers/orders/% is provided by Views.

  $items['admin/store/settings/orders'] = array(
    'title' => 'Orders',
    'description' => 'Configure the workflow and fields for orders.',
    'route_name' => 'uc_order.workflow',
  );
  $items['admin/store/settings/orders/workflow'] = array(
    'title' => 'Workflow',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/store/orders'] = array(
    'title' => 'Orders',
    'description' => 'View and process orders.',
    'route_name' => 'uc_order.order_admin',
    'weight' => -10,
    'position' => 'left',
  );
  // admin/store/orders/view is provided by Views.
  $items['admin/store/orders/create'] = array(
    'title' => 'Create order',
    'description' => 'Create an empty new order.',
    'route_name' => 'uc_order.create',
    'weight' => -5,
  );
  $items['admin/store/orders/create/%user'] = array(
    'title' => 'Create order for this customer',
    'description' => 'Create an empty new order.',
    'page callback' => 'uc_order_create_for_user',
    'page arguments' => array(4),
    'access arguments' => array('create orders'),
    'file' => 'uc_order.admin.inc',
  );
  // admin/store/orders/search is provided by Views.
  $items['admin/store/orders/address_book'] = array(
    'title' => 'Select address',
    'page callback' => 'uc_order_address_book',
    'access arguments' => array('edit orders'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_order.admin.inc',
  );
  $items['admin/store/orders/customer'] = array(
    'title' => 'Select customer',
    'page callback' => 'uc_order_select_customer',
    'page arguments' => array(NULL),
    'access arguments' => array('edit orders'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_order.admin.inc',
  );
  $items['admin/store/orders/%uc_order/add_line_item/%'] = array(
    'title' => 'Add a line item',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_order_add_line_item_form', 3, 5),
    'access arguments' => array('edit orders'),
    'type' => MENU_CALLBACK,
    'file' => 'uc_order.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function uc_order_menu_alter(&$items) {
  // Adjust the Field UI tabs on admin/store/settings/orders.
  $items['admin/store/settings/orders/products/fields']['title'] = 'Ordered product fields';
  $items['admin/store/settings/orders/products/fields']['weight'] = 3;
  // Disable field display settings for ordered products, as we don't use this anywhere (yet).
  unset($items['admin/store/settings/orders/products/display']);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function uc_order_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'admin/store/customers/orders/%') {
    $uid = $router_item['page_arguments'][0];
    $item = menu_get_item('admin/store/orders/create/' . $uid);
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_admin_paths().
 */
function uc_order_admin_paths() {
  return array(
    // Don't show invoices with the admin theme, overlay, etc.
    'admin/store/orders/*/invoice*' => FALSE,
  );
}

/**
 * Implements hook_page_build().
 */
function uc_order_page_build(&$page) {
  $path = drupal_get_path('module', 'uc_order');
  $page['#attached']['css'][$path . '/css/uc_order.css'] = array('every_page' => TRUE);

  // Load uc_order.js on all order and customer admin pages.
  if (arg(0) == 'admin' && arg(1) == 'store' && (arg(2) == 'orders' || arg(2) == 'customers')) {
    $page['#attached']['js'][$path . '/js/uc_order.js'] = array('every_page' => TRUE);
    $page['#attached']['js'][] = array(
      'type' => 'setting',
      'data' => array('ucURL' => array(
        'adminOrders' => url('admin/store/orders/'),
      )),
    );
  }
}

/**
 * Implements hook_theme().
 */
function uc_order_theme($existing, $type, $theme, $path) {
  $theme_hooks = array(
    'uc_order_invoice' => array(
      'template' => 'uc-order-invoice',
      'variables' => array(
        'order' => NULL,
        'op' => 'view',
        'template' => '',
        'thank_you_message' => FALSE,
        'help_text' => FALSE,
        'email_text' => FALSE,
        'store_footer' => FALSE,
        'business_header' => FALSE,
        'shipping_method' => FALSE,
      ),
    ),
    'uc_order_invoice_page' => array(
      'variables' => array('content' => NULL),
      'template' => 'uc-order-invoice-page',
    ),
    'uc_order_status_table' => array(
      'render element' => 'form',
      'file' => 'uc_order.admin.inc',
    ),
    'uc_order_edit_form' => array(
      'render element' => 'form',
      'file' => 'uc_order.admin.inc',
    ),
    'uc_order_pane_line_items' => array(
      'render element' => 'form',
      'file' => 'uc_order.order_pane.inc',
    ),
  );

  $theme_hooks += array(
    'uc_order_invoice__admin' => array(
      'template' => 'uc-order-invoice--admin',
      'variables' => $theme_hooks['uc_order_invoice']['variables'],
    ),
  );

  return $theme_hooks;
}

/**
 * Implements hook_entity_view_mode_info().
 */
function uc_order_entity_view_mode_info() {
  $view_modes['uc_order']['admin'] = array(
    'label' => t('Admin view'),
  );
  $view_modes['uc_order']['customer'] = array(
    'label' => t('Customer view'),
    'custom_settings' => TRUE,
  );
  $view_modes['uc_order_product']['full'] = array(
    'label' => t('Normal view'),
  );
  $view_modes['uc_order_product']['cart'] = array(
    'label' => t('Cart view'),
  );
  return $view_modes;
}

/**
 * Implements hook_entity_bundle_info().
 */
function uc_order_entity_bundle_info() {
  $bundles['uc_order']['uc_order']['label'] = t('Order');
  $bundles['uc_order_product']['uc_order_product']['label'] = t('Order product');
  return $bundles;
}

/**
 * Implements hook_permission().
 */
function uc_order_permission() {
  return array(
    'administer order workflow' => array(
      'title' => t('Administer order workflow'),
    ),
    'view customers' => array(
      'title' => t('View customers'),
    ),
    'view own orders' => array(
      'title' => t('View own orders'),
    ),
    'view own invoices' => array(
      'title' => t('View own invoices'),
    ),
    'view all orders' => array(
      'title' => t('View all orders'),
    ),
    'create orders' => array(
      'title' => t('Create orders'),
    ),
    'edit orders' => array(
      'title' => t('Edit orders'),
    ),
    'delete orders' => array(
      'title' => t('Delete orders'),
    ),
    'unconditionally delete orders' => array(
      'title' => t('Unconditionally delete orders'),
    ),
  );
}

/**
 * Implements hook_field_extra_fields().
 */
function uc_order_field_extra_fields() {
  $panes = module_invoke_all('uc_order_pane');
  $extra = array();

  foreach ($panes as $id => $pane) {
    $extra_field = array(
      'label' => $pane['title'],
      'description' => $pane['desc'],
      'weight' => $pane['weight'],
    );

    if (in_array('edit', $pane['show'])) {
      $extra['uc_order']['uc_order']['form'][$id] = $extra_field;
    }

    if (in_array('view', $pane['show']) || in_array('customer', $pane['show'])) {
      $extra['uc_order']['uc_order']['display'][$id] = $extra_field;
    }
  }

  return $extra;
}

/**
 * Implements hook_user_view().
 */
function uc_order_user_view($account, $view_mode) {
  global $user;

  if ($view_mode == 'full' && $user->isAuthenticated() && (($user->id() == $account->id() && user_access('view own orders')) || user_access('view all orders'))) {
    $account->content['orders'] = array(
      '#type' => 'item',
      '#title' => t('Orders'),
      '#markup' => l(t('Click here to view your order history.'), 'user/' . $account->id() . '/orders'),
    );
  }
}

/**
 * Implements hook_mail().
 */
function uc_order_mail($key, &$message, $params) {
  $langcode = isset($message['language']) ? $message['language']->language : NULL;

  // Build the appropriate message parameters based on the e-mail key.
  switch ($key) {
    // Setup an e-mailed invoice.
    case 'invoice':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      $message['subject'] = t('Your Order Invoice', array(), array('langcode' => $langcode));
      $message['from'] = uc_store_email_from();
      $message['body'][] = theme('uc_order_invoice', array('order' => $params['order'], 'op' => 'admin-mail'));
      break;

    // Setup a custom e-mail defined by an action on a predicate.
    case 'action-mail':
      // Assemble an email message from the conditional actions settings.
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      $message['from'] = $params['from'];

      // Perform token replacement on the subject and body.
      $token_service = Drupal::token();
      $subject = $token_service->replace($params['subject'], $params['replacements'], $langcode ? array('language' => $message['language']) : array());
      $body = $token_service->replace($params['message'], $params['replacements'], $langcode ? array('language' => $message['language']) : array());

      // Strip newline characters from e-mail subjects.
      // @todo: Maybe drupal_mail_send() should do this?
      $message['subject'] = str_replace(array("\r\n", "\r", "\n"), ' ', $subject);

      // Apply an input format to the message body if specified.
      if (isset($params['format'])) {
        $message['body'] = explode("\n", check_markup($body, $params['format'], $langcode));
      }
      else {
        $message['body'] = explode("\n", $body);
      }

      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function uc_order_form_views_exposed_form_alter(&$form, &$form_state) {
  if (substr($form['#id'], 0, 29) == 'views-exposed-form-uc-orders-') {
    $form['#submit'][] = 'uc_order_form_views_exposed_form_submit';

    if ($form['#id'] == 'views-exposed-form-uc-orders-search' && !module_exists('date_views')) {
      drupal_set_message(t('Download the <a href="@url">Date module</a> and enable Date Views to allow searching orders by date.', array('@url' => 'http://drupal.org/project/date')), 'warning');
    }
  }
}

/**
 * Redirects if an order ID was entered in the exposed field.
 */
function uc_order_form_views_exposed_form_submit($form, &$form_state) {
  if (!empty($form_state['values']['order_id']) && entity_load('uc_order', $form_state['values']['order_id'])) {
    $form_state['redirect'] = 'admin/store/orders/' . $form_state['values']['order_id'];
    $form_state['no_redirect'] = FALSE;
  }
}

/**
 * Implements hook_uc_order_pane().
 */
function uc_order_uc_order_pane() {
  $panes['print_button'] = array(
    'callback' => 'uc_order_pane_print_button',
    'title' => t('Print button'),
    'display title' => '',
    'desc' => t("Button to open a printable invoice."),
    'class' => 'abs-left',
    'weight' => -10,
    'show' => array('customer'),
  );
  $panes['ship_to'] = array(
    'callback' => 'uc_order_pane_ship_to',
    'title' => t('Ship to'),
    'desc' => t("Manage the order's shipping address and contact information."),
    'class' => 'pos-left',
    'weight' => 1,
    'show' => array('view', 'edit', 'customer'),
  );
  $panes['bill_to'] = array(
    'callback' => 'uc_order_pane_bill_to',
    'title' => t('Bill to'),
    'desc' => t("Manage the order's billing address and contact information."),
    'class' => 'pos-left',
    'weight' => 2,
    'show' => array('view', 'edit', 'customer'),
  );
  $panes['customer'] = array(
    'callback' => 'uc_order_pane_customer',
    'title' => t('Customer info'),
    'desc' => t("Manage the information for the customer's user account."),
    'class' => 'pos-left',
    'weight' => 3,
    'show' => array('view', 'edit'),
  );
  $panes['products'] = array(
    'callback' => 'uc_order_pane_products',
    'title' => t('Products'),
    'desc' => t('Manage the products an order contains.'),
    'class' => 'abs-left',
    'weight' => 5,
    'show' => array('view', 'edit', 'customer'),
  );
  $panes['line_items'] = array(
    'callback' => 'uc_order_pane_line_items',
    'title' => t('Line items'),
    'display title' => '',
    'desc' => t("View and modify an order's line items."),
    'class' => 'abs-left',
    'weight' => 6,
    'show' => array('view', 'edit', 'customer'),
  );
  $panes['order_comments'] = array(
    'callback' => 'uc_order_pane_order_comments',
    'title' => t('Order comments'),
    'desc' => t('View the order comments, used for communicating with customers.'),
    'class' => 'abs-left',
    'weight' => 8,
    'show' => array('view', 'customer'),
  );
  $panes['admin_comments'] = array(
    'callback' => 'uc_order_pane_admin_comments',
    'title' => t('Admin comments'),
    'desc' => t('View the admin comments, used for administrative notes and instructions.'),
    'class' => 'abs-left',
    'weight' => 9,
    'show' => array('view', 'edit'),
  );
  $panes['update'] = array(
    'callback' => 'uc_order_pane_update',
    'title' => t('Update order'),
    'desc' => t("Update an order's status or add comments to an order."),
    'class' => 'abs-left',
    'weight' => 10,
    'show' => array('view'),
  );

  return $panes;
}

/**
 * Implements hook_uc_order_state().
 */
function uc_order_uc_order_state() {
  $states['canceled'] = array(
    'title' => t('Canceled'),
    'weight' => -20,
    'scope' => 'specific',
  );
  $states['in_checkout'] = array(
    'title' => t('In checkout'),
    'weight' => -10,
    'scope' => 'specific',
  );
  $states['post_checkout'] = array(
    'title' => t('Post checkout'),
    'weight' => 0,
    'scope' => 'general',
  );
  $states['completed'] = array(
    'title' => t('Completed'),
    'weight' => 20,
    'scope' => 'general',
  );

  return $states;
}

/**
 * Implements hook_uc_line_item().
 */
function uc_order_uc_line_item() {
  $items['subtotal'] = array(
    'title' => t('Subtotal'),
    'weight' => 0,
    'stored' => FALSE,
    'calculated' => FALSE,
    'callback' => 'uc_line_item_subtotal',
  );
  $items['generic'] = array(
    'title' => t('Empty line'),
    'weight' => 2,
    'stored' => TRUE,
    'add_list' => TRUE,
    'calculated' => TRUE,
    'callback' => 'uc_line_item_generic',
  );
  $items['total'] = array(
    'title' => t('Total'),
    'weight' => 15,
    'stored' => FALSE,
    'calculated' => FALSE,
    'display_only' => TRUE,
    'callback' => 'uc_line_item_total',
  );

  return $items;
}

/**
 * Entity API "uri callback" for uc_order entity.
 *
 * @param $order
 *   The order to return the URI for.
 */
function uc_order_uri($order) {
  return array(
    'path' => 'admin/store/orders/' . $order->id(),
  );
}

/**
 * Generates and saves a new order.
 *
 * @param $uid
 *   The user ID to assign the order to.
 * @param $state
 *   The initial state of the order.
 */
function uc_order_new($uid = 0, $state = 'in_checkout') {
  $order = entity_create('uc_order', array(
    'uid' => $uid,
    'order_status' => uc_order_state_default($state),
  ));

  $order->save();

  uc_order_module_invoke('new', $order, NULL);

  return $order;
}

/**
 * Save a product to an order.
 */
function uc_order_product_save($order_id, $product) {
  $product->order_id = $order_id;
  return $product->save();
}

/**
 * Merge fields from their associated nodes into a set of order products.
 *
 * @param $products
 *   An array of order_products.
 * @param $published
 *   TRUE to load only published nodes, FALSE to load all nodes.
 *
 * @return
 *   TRUE if the merge was successful for all products in the set. FALSE
 *   otherwise (i.e. if the associated product node no longer exists).
 */
function uc_order_product_revive($products, $published = TRUE) {
  // Allow invocation for a single product.
  if (!is_array($products)) {
    $products = array($products);
  }

  // Load the nodes associated with each order product.
  $nids = array();
  foreach ($products as $product) {
    $nids[] = $product->nid->value;
  }
  $nodes = node_load_multiple($nids);

  // Merge in fields from any nodes that still exist (but don't override order
  // product fields that are already set).
  $return = TRUE;
  foreach ($products as &$product) {
    if (!empty($nodes[$product->nid->value]) && (!$published || $nodes[$product->nid->value]->isPublished())) {
      foreach (get_object_vars($nodes[$product->nid->value]) as $key => $value) {
        if (!property_exists($product, $key)) {
          $product->$key = $value;
        }
      }
      // Order products are always variants.
      $product->variant = TRUE;
    }
    else {
      $return = FALSE;
    }
  }

  return $return;
}

/**
 * Loads one order entity from the database.
 *
 * @param int $order_id
 *   The order ID.
 * @param bool $reset
 *   (optional) Whether to reset the internal cache. Defaults to FALSE.
 *
 * @return Drupal\uc_order\UcOrder|false
 *   A fully-populated order entity, or FALSE if the order is not found.
 */
function uc_order_load($order_id, $reset = FALSE) {
  return entity_load('uc_order', $order_id, $reset);
}

/**
 * Returns an array of comments or admin comments for an order.
 */
function uc_order_comments_load($order_id, $admin = FALSE) {
  $table = $admin ? 'uc_order_admin_comments' : 'uc_order_comments';
  $query = db_select($table, 'oc')
    ->fields('oc')
    ->condition('order_id', $order_id)
    ->orderBy('oc.created')
    ->orderBy('oc.comment_id');

  if (!$admin) {
    $query->leftJoin('uc_order_statuses', 'os', 'oc.order_status = os.order_status_id');
    $query->fields('os');
  }

  $comments = $query->execute()->fetchAll();

  return $comments;
}

/**
 * Inserts a comment, $type being either 'order' or 'admin'.
 */
function uc_order_comment_save($order_id, $uid, $message, $type = 'admin', $status = 'pending', $notify = FALSE) {
  if ($type == 'admin') {
    db_insert('uc_order_admin_comments')
      ->fields(array(
        'order_id' => $order_id,
        'uid' => $uid,
        'message' => $message,
        'created' => REQUEST_TIME,
      ))
      ->execute();
  }
  elseif ($type == 'order') {
    db_insert('uc_order_comments')
      ->fields(array(
        'order_id' => $order_id,
        'uid' => $uid,
        'message' => $message,
        'order_status' => $status,
        'notified' => $notify ? 1 : 0,
        'created' => REQUEST_TIME,
      ))
      ->execute();
  }
}

/**
 * Returns an array containing an order's line items ordered by weight.
 *
 * @param $order
 *   An order object whose line items are to be loaded.
 * @param $stored
 *   Boolean flag. If TRUE, only line items stored in the database are loaded.
 *   If FALSE, only line items not stored in the database are loaded.
 *   This distinction is made because the non-stored line items may depend on
 *   the amounts of all of the stored line items.
 *
 * @return
 *   An array of line items, which are arrays containing the following keys:
 *   - line_item_id: The line item id.
 *   - type: The line item type.
 *   - title: The line item title.
 *   - amount: The line item amount.
 *   - weight: The line item weight.
 */
function uc_order_load_line_items($order) {
  $items = array();

  $result = db_query("SELECT * FROM {uc_order_line_items} WHERE order_id = :id", array(':id' => $order->id()));
  foreach ($result as $row) {
    $item = array(
      'line_item_id' => $row->line_item_id,
      'type' => $row->type,
      'title' => $row->title,
      'amount' => $row->amount,
      'weight' => $row->weight,
      'data' => unserialize($row->data),
    );
    drupal_alter('uc_line_item', $item, $order);
    $items[] = $item;
  }

  // Set stored line items so hook_uc_line_item_alter() can access them.
  $order->line_items = $items;

  foreach (_uc_line_item_list() as $type) {
    if ($type['stored'] == FALSE && empty($type['display_only']) && !empty($type['callback']) && function_exists($type['callback'])) {
      $result = $type['callback']('load', $order);
      if ($result !== FALSE && is_array($result)) {
        foreach ($result as $line) {
          $item = array(
            'line_item_id' => $line['id'],
            'type' => $type['id'],
            'title' => $line['title'],
            'amount' => $line['amount'],
            'weight' => isset($line['weight']) ? $line['weight'] : $type['weight'],
            'data' => isset($line['data']) ? $line['data'] : array(),
          );
          drupal_alter('uc_line_item', $item, $order);
          $items[] = $item;
        }
      }
    }
  }

  usort($items, 'uc_weight_sort');

  return $items;
}

/**
 * Returns an order's line items ordered by weight, prepared for display.
 *
 * @param $order
 *   An order object whose line items are to be loaded.
 *
 * @return
 *   An array of line items, which are arrays containing the following keys:
 *   - type: The line item type.
 *   - title: The line item title.
 *   - amount: The line item amount.
 *   - weight: The line item weight.
 */
function uc_order_load_line_items_display($order) {
  $temp = clone $order;
  $line_items = uc_order_load_line_items($order);
//  $temp->line_items = &$line_items;

  $items = _uc_line_item_list();
  foreach ($items as $item) {
    if (!empty($item['display_only'])) {
      $result = $item['callback']('display', $temp);
      if (is_array($result)) {
        foreach ($result as $line) {
          $line_items[] = array(
            'type' => $item['id'],
            'title' => $line['title'],
            'amount' => $line['amount'],
            'weight' => isset($line['weight']) ? $line['weight'] : $item['weight'],
            'data' => isset($line['data']) ? $line['data'] : array(),
          );
        }
      }
    }
  }
  foreach ($line_items as &$item) {
    $item['formatted_amount'] = uc_currency_format($item['amount']);
  }

  usort($line_items, 'uc_weight_sort');

  return $line_items;
}

/**
 * Updates an order's status as long as no one objects.
 *
 * @param $order_id
 *   The ID of the order to be updated.
 * @param $status
 *   The new status ID we want to move the order to.
 *
 * @return
 *   TRUE or FALSE depending on the success of the update.
 */
function uc_order_update_status($order_id, $status) {
  // Return FALSE if an invalid $status is specified.
  if (uc_order_status_data($status, 'id') == NULL) {
    return FALSE;
  }

  $order = uc_order_load($order_id);

  // Attempt the update if the order exists.
  if ($order !== FALSE) {
    // Return TRUE if the order status is already set.
    if ($order->getStatusId() == $status) {
      return TRUE;
    }

    // Return FALSE if any module says the update is not good to go.
    foreach (module_implements('uc_order') as $module) {
      $function = $module . '_uc_order';
      // $order must be passed by reference.
      if (function_exists($function) && $function('can_update', $order, $status) === FALSE) {
        return FALSE;
      }
    }

    // Otherwise perform the update and log the changes.
    db_update('uc_orders')
      ->fields(array(
        'order_status' => $status,
        'modified' => REQUEST_TIME,
      ))
      ->condition('order_id', $order_id)
      ->execute();
    uc_order_module_invoke('update', $order, $status);

    $change = array(t('Order status') => array('old' => uc_order_status_data($order->getStatusId(), 'title'), 'new' => uc_order_status_data($status, 'title')));
    uc_order_log_changes($order->id(), $change);

    $updated = uc_order_load($order_id, TRUE);
    // rules_invoke_event('uc_order_status_update', $order, $updated);

    return TRUE;
  }

  // Return FALSE if the order didn't exist.
  return FALSE;
}

/**
 * Logs changes made to an order.
 *
 * @param $order_id
 *   The ID of the order that was changed.
 * @param $changes
 *   An array of changes. Two formats are allowed:
 *   - keys: Keys being the name of the field changed and the values being
 *     associative arrays with the keys 'old' and 'new' to represent the old
 *     and new values of the field. These will be converted into a changed
 *     message.
 *   - string: A pre-formatted string describing the change. This is useful for
 *     logging details like payments.
 *
 * @return
 *   TRUE or FALSE depending on whether or not changes were logged.
 */
function uc_order_log_changes($order_id, $changes) {
  global $user;

  if (count($changes) == 0) {
    return FALSE;
  }

  foreach ($changes as $key => $value) {
    if (is_array($value)) {
      $items[] = t('@key changed from %old to %new.', array('@key' => $key, '%old' => $value['old'], '%new' => $value['new']));
    }
    elseif (is_string($value)) {
      $items[] = $value;
    }
  }

  db_insert('uc_order_log')
    ->fields(array(
      'order_id' => $order_id,
      'uid' => $user->id(),
      'changes' => theme('item_list', array('items' => $items)),
      'created' => REQUEST_TIME,
    ))
    ->execute();

  return TRUE;
}

/**
 * Returns an address from an order object.
 *
 * @param $order
 *   An order object.
 * @param $type
 *   Either 'delivery' or 'billing'.
 */
function uc_order_address($order, $type) {
  $name = $order->{$type . '_first_name'} . ' ' . $order->{$type . '_last_name'};
  $address = uc_address_format(
    $order->{$type . '_first_name'},
    $order->{$type . '_last_name'},
    $order->{$type . '_company'},
    $order->{$type . '_street1'},
    $order->{$type . '_street2'},
    $order->{$type . '_city'},
    $order->{$type . '_zone'},
    $order->{$type . '_postal_code'},
    $order->{$type . '_country'}
  );

  if (\Drupal::config('uc_store.settings')->get('capitalize_address')) {
    $address = \Drupal\Component\Utility\Unicode::strtoupper($address);
  }

  return $address;
}

/**
 * Invokes hook_uc_order() in every module.
 *
 * We cannot use module_invoke() for this, because the arguments need to
 * be passed by reference.
 */
function uc_order_module_invoke($op, &$order, $edit) {
  foreach (module_implements('uc_order') as $module) {
    $function = $module . '_uc_order';
    if (function_exists($function)) {
      $function($op, $order, $edit);
    }
  }
}

/**
 * Determines whether a product is shippable or not.
 */
function uc_order_product_is_shippable($product) {
  // Return FALSE if the product form specifies this as not shippable.
  if (empty($product->data['shippable'])) {
    return FALSE;
  }

  // See if any other modules have a say in the matter...
  $result = module_invoke_all('uc_order_product_can_ship', $product);

  // Return TRUE by default.
  if (empty($result) || in_array(TRUE, $result)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Determines if an order is shippable.
 *
 * An order can be shipped if any of its products can be shipped.
 */
function uc_order_is_shippable($order) {
  if (!is_array($order->products) || empty($order->products)) {
    return FALSE;
  }

  foreach ($order->products as $product) {
    if (uc_order_product_is_shippable($product)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Preprocesses a formatted invoice with an order's data.
 *
 * @see uc_order--admin.tpl.php
 * @see uc_order--customer.tpl.php
 */
function template_preprocess_uc_order_invoice(&$variables) {
  $order = &$variables['order'];

  switch ($variables['op']) {
    case 'checkout-mail':
      $variables['thank_you_message'] = TRUE;
    case 'admin-mail':
      $variables['help_text'] = TRUE;
      $variables['email_text'] = TRUE;
      $variables['store_footer'] = TRUE;
    case 'view':
    case 'print':
      $variables['business_header'] = TRUE;
      $variables['shipping_method'] = TRUE;
      break;
  }

  $variables['shippable'] = uc_order_is_shippable($order);

  $variables['products'] = array();
  if (!empty($order->products)) {
    $display = entity_view_multiple($order->products, 'full');
    foreach ($order->products as $id => $product) {
      $variables['products'][$id] = new stdClass;
      $variables['products'][$id]->title = $product->title->value;
      $variables['products'][$id]->qty = $product->qty->value;
      $variables['products'][$id]->model = $product->model->value;
      $variables['products'][$id]->total_price = render($display[$product->order_product_id->value]['total']);
      if ($product->qty->value > 1) {
        $variables['products'][$id]->individual_price = t('(!price each)', array('!price' => uc_currency_format($display[$product->order_product_id->value]['price']['#price'])));
      }
      else {
        $variables['products'][$id]->individual_price = '';
      }

      $variables['products'][$id]->details = '';
      if (!empty($product->data['attributes'])) {
        $attributes = array();
        foreach ($product->data['attributes'] as $attribute => $option) {
          $attributes[] = t('@attribute: @options', array('@attribute' => $attribute, '@options' => implode(', ', (array)$option)));
        }
        $variables['products'][$id]->details .= theme('item_list', array('items' => $attributes));
      }
    }
  }

  $variables['line_items'] = uc_order_load_line_items_display($variables['order']);
  $order->line_items = $variables['line_items'];

  // Generate tokens to use as template variables.
  $types = array(
    'uc_order' => $order,
  );

  $token_service = Drupal::token();
  $token_info = $token_service->getInfo();

  $replacements = array();
  foreach (array('site', 'store', 'uc_order') as $type) {
    $replacements[$type] = $token_service->generate($type, drupal_map_assoc(array_keys($token_info['tokens'][$type])), $types);
  }

  foreach ($replacements as $type => $tokens) {
    foreach ($tokens as $token => $value) {
      $key = str_replace('-', '_', $type . '_' . $token);
      $key = str_replace('uc_', '', $key);
      $variables[$key] = $value;
    }
  }

  // Add hook suggestions, default to customer template.
  if ($variables['template']) {
    $variables['theme_hook_suggestions'][] =  'uc_order_invoice__' . $variables['template'];
  }
}

/**
 * Preprocesses a printable invoice page.
 *
 * @see uc_order-invoice-page.tpl.php
 */
function template_preprocess_uc_order_invoice_page(&$variables) {
  $language_interface = Drupal::languageManager()->getLanguage();

  // HTML element attributes.
  $variables['html_attributes'] = new Attribute;
  $variables['html_attributes']['lang'] = $language_interface->langcode;
  $variables['html_attributes']['dir'] = $language_interface->direction ? 'rtl' : 'ltr';

  $site_config = config('system.site');
  // Construct page title.
  if (drupal_get_title()) {
    $head_title = array(
      'title' => strip_tags(drupal_get_title()),
      'name' => check_plain($site_config->get('name')),
    );
  }
  else {
    $head_title = array('name' => check_plain($site_config->get('name')));
    if ($site_config->get('slogan')) {
      $head_title['slogan'] = strip_tags(filter_xss_admin($site_config->get('slogan')));
    }
  }

  // Add favicon.
  if (theme_get_setting('features.favicon')) {
    $favicon = theme_get_setting('favicon.url');
    $type = theme_get_setting('favicon.mimetype');
    drupal_add_html_head_link(array('rel' => 'shortcut icon', 'href' => drupal_strip_dangerous_protocols($favicon), 'type' => $type));
  }
  $variables['head'] = drupal_get_html_head();

  // Set the default language if necessary.
  $language = isset($GLOBALS['language']) ? $GLOBALS['language'] : language_default();

  $variables['head_title'] = implode(' | ', $head_title);
}

/**
 * Returns a sorted list of the order states defined in the various modules.
 *
 * @param $scope
 *   Specify the scope for the order states you want listed - all, general, or
 *   specific. States with a general scope are used on general lists and pages.
 * @param $sql
 *   Pass this parameter as TRUE to alter the return value for a SQL query.
 *
 * @return
 *   Either an array of state arrays or a string containing an array of state
 *   ids for use in a SQL query.
 */
function uc_order_state_list($scope = 'all', $sql = FALSE) {
  $states = array();

  foreach (module_invoke_all('uc_order_state') as $id => $state) {
    // Preserve backward compatibility for states with no key specified.
    if (is_numeric($id)) {
      $id = $state['id'];
    }
    else {
      $state['id'] = $id;
    }

    if ($scope == 'all' || $state['scope'] == $scope) {
      $states[$id] = $state;
    }
  }
  uasort($states, 'uc_weight_sort');

  return $sql ? array_keys($states) : $states;
}

/**
 * Returns a bit of data from a state array based on the state ID and array key.
 *
 * @param $state_id
 *   The ID of the order state you want to get data from.
 * @param $key
 *   The key in the state array whose value you want: id, title, weight, scope.
 *
 * @return
 *   The value of the key you specify.
 */
function uc_order_state_data($state_id, $key) {
  static $states;

  if (empty($states)) {
    $states = uc_order_state_list();
  }

  return $states[$state_id][$key];
}

/**
 * Returns the default order status for a particular order state.
 *
 * @param $state_id
 *   The ID of the order state whose default status you want to find.
 *
 * @return
 *   A string containing the default order status ID for the specified state.
 */
function uc_order_state_default($state_id) {
  static $default;

  // Return the default value if it exists.
  if (isset($default[$state_id])) {
    return $default[$state_id];
  }

  // Attempt to get the default state from the form.
  $default[$state_id] = variable_get('uc_state_' . $state_id . '_default', NULL);

  // If it is not found, pick the lightest status for this state.
  if (empty($default[$state_id])) {
    $statuses = uc_order_status_list($state_id);
    $default[$state_id] = $statuses[0]['id'];
  }

  return $default[$state_id];
}

/**
 * Returns a sorted list of order statuses, sortable by order state/scope.
 *
 * @param $scope
 *   Specify the scope for the order statuses you want listed - all, general,
 *   specific, or any order state id. Defaults to all.
 * @param $sql
 *   Pass this parameter as TRUE to alter the return value for a SQL query.
 * @param $action
 *   Empty by default. Set to rebuild to load the order statuses from scratch,
 *   disregarding the current cached value for the specified $scope.
 *
 * @return
 *   Either an array of status arrays or a string containing an array of status
 *   ids for use in a SQL query.
 */
function uc_order_status_list($scope = 'all', $sql = FALSE, $action = '') {
  static $statuses;

  if (!isset($statuses[$scope]) || $action == 'rebuild') {
    switch ($scope) {
      case 'all':
        $result = db_query("SELECT * FROM {uc_order_statuses}");
        break;
      case 'general':
      case 'specific':
        $result = db_query("SELECT * FROM {uc_order_statuses} WHERE state IN (:states)", array(':states' => uc_order_state_list($scope, TRUE)));
        break;
      default:
        $result = db_query("SELECT * FROM {uc_order_statuses} WHERE state = :scope", array(':scope' => $scope));
        break;
    }

    $statuses[$scope] = array();
    while ($status = $result->fetchAssoc()) {
      $status['id'] = $status['order_status_id'];
      unset($status['order_status_id']);

      $statuses[$scope][] = $status;
    }
    usort($statuses[$scope], 'uc_weight_sort');
  }

  if ($sql) {
    $ids = array();
    foreach ($statuses[$scope] as $status) {
      $ids[] = $status['id'];
    }
    return $ids;
  }

  return $statuses[$scope];
}

/**
 * Returns a bit of data from a status array based on status ID and array key.
 *
 * @param $status_id
 *   The ID of the order status you want to get data from.
 * @param $key
 *   The key in the status array whose value you want: id, title, state, weight.
 *
 * @return
 *   The value of the key you specify.
 */
function uc_order_status_data($status_id, $key) {
  static $statuses;

  if (empty($statuses)) {
    $data = uc_order_status_list();
    foreach ($data as $status) {
      $statuses[$status['id']] = $status;
    }
  }

  return $statuses[$status_id][$key];
}

/**
 * Returns an option list of order statuses.
 */
function uc_order_status_options_list() {
  $options = array();
  foreach (uc_order_status_list() as $status) {
    $options[$status['id']] = $status['title'];
  }
  return $options;
}

/**
 * Returns the actions a user may perform on an order.
 *
 * @param $order
 *   The order to return the actions for.
 *
 * @return
 *   A renderable set of operation links.
 */
function uc_order_actions($order, $icon_html = FALSE) {
  global $user;

  $actions = array();

  if (user_access('view all orders')) {
    $actions['view'] = array(
      'title' => t('View'),
      'href' => 'admin/store/orders/' . $order->id(),
      'weight' => 0,
    );
    $actions['print'] = array(
      'title' => t('Print'),
      'href' => 'admin/store/orders/' . $order->id() . '/invoice/print',
      'weight' => 5,
    );
  }
  else {
    if ($order->access('view')) {
      $actions['view'] = array(
        'title' => t('View'),
        'href' => 'user/' . $user->id() . '/orders/' . $order->id(),
        'weight' => 0,
      );
    }
    if ($order->access('invoice')) {
      $actions['print'] = array(
        'title' => t('Print'),
        'href' => 'user/' . $user->id() . '/orders/' . $order->id() . '/print',
        'weight' => 5,
      );
    }
  }

  if ($order->access('edit')) {
    $actions['edit'] = array(
      'title' => t('Edit'),
      'href' => 'admin/store/orders/' . $order->id() . '/edit',
      'weight' => 10,
    );
  }

  if ($order->access('delete')) {
    $actions['delete'] = array(
      'title' => t('Delete'),
      'href' => 'admin/store/orders/' . $order->id() . '/delete',
      'weight' => 20,
    );
  }

  $extra = module_invoke_all('uc_order_actions', $order);
  if (count($extra)) {
    $actions = array_merge($actions, $extra);
  }
  drupal_alter('uc_order_actions', $actions, $order);

  return array(
    '#type' => 'operations',
    '#links' => $actions,
  );
}

/**
 * Implements hook_date_views_tables().
 */
function uc_order_date_views_tables() {
  return array('uc_orders');
}

/**
 * Implements hook_date_views_fields().
 *
 * All modules that create custom fields that use the
 * 'views_handler_field_date' handler can provide
 * additional information here about the type of
 * date they create so the date can be used by
 * the Date API views date argument and date filter.
 */
function uc_order_date_views_fields($field) {
  $values = array(
    // The type of date: DATE_UNIX, DATE_ISO, DATE_DATETIME.
    'sql_type' => DATE_UNIX,
    // Timezone handling options: 'none', 'site', 'date', 'utc' .
    'tz_handling' => 'site',
    // Needed only for dates that use 'date' tz_handling.
    'timezone_field' => '',
    // Needed only for dates that use 'date' tz_handling.
    'offset_field' => '',
    // Array of "table.field" values for related fields that should be
    // loaded automatically in the Views SQL.
    'related_fields' => array(),
    // Granularity of this date field's db data.
    'granularity' => array('year', 'month', 'day', 'hour', 'minute', 'second'),
  );

  switch ($field) {
    case 'uc_orders.created':
    case 'uc_orders.modified':
      return $values;
  }
}

/**
 * Implements hook_action_info().
 */
function uc_order_action_info() {
  return array(
    'uc_order_action_set_status' => array(
      'label' => t('Set order status'),
      'type' => 'uc_order',
      'configurable' => TRUE,
      'triggers' => array('any'),
    ),
    'uc_order_action_print' => array(
      'label' => t('Print invoice'),
      'type' => 'uc_order',
      'aggregate' => TRUE,
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'uc_order_action_delete' => array(
      'label' => t('Delete order'),
      'type' => 'uc_order',
      'configurable' => FALSE,
      'behavior' => array('deletes_property'),
      'triggers' => array('any'),
    ),
  );
}

/**
 * Action implementation: sets the status of an order.
 */
function uc_order_action_set_status($order, $context = array()) {
  $update = uc_order_update_status($order->id(), $context['status']);

  if ($update && $context['notify']) {
    // Update order object, as uc_order_update_status() cannot.
    $order->setStatusId($context['status']);

    // rules_invoke_event('uc_order_status_email_update', $order);
  }
}

/**
 * Action form: selects the order status to be used.
 */
function uc_order_action_set_status_form($context) {
  $form['status'] = array(
    '#type' => 'select',
    '#title' => t('Order status'),
    '#default_value' => @$context['status'],
    '#options' => uc_order_status_options_list(),
  );
  $form['notify'] = array(
    '#type' => 'checkbox',
    '#title' => t('Send e-mail notification on update.'),
    '#default_value' => @$context['notify'],
  );
  return $form;
}

/**
 * Submit callback: selects the order status to be used.
 */
function uc_order_action_set_status_submit($form, $form_state) {
  return array(
    'status' => $form_state['values']['status'],
    'notify' => $form_state['values']['notify'],
  );
}

/**
 * Action implementation: prints multiple invoices.
 */
function uc_order_action_print($orders, $context = array()) {
  $output = '';

  foreach ($orders as $order) {
    $output .= '<div style="page-break-after: always;">';
    $output .= theme('uc_order_invoice', array(
      'order' => $order,
      'op' => 'print',
    ));
    $output .= '</div>';
  }

  print '<html><head><title>Invoice</title></head>';
  print '<body onload="print();">';
  print $output;
  print '</body></html>';
  exit;
}

/**
 * Action implementation: delete an order.
 */
function uc_order_action_delete($order) {
  $order->delete();
}
