<?php

/**
 * @file
 * United States Postal Service (USPS) shipping quote module.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function uc_usps_theme() {
  return array(
    'uc_usps_option_label' => array(
      'variables' => array(
        'service'  => NULL,
        'packages' => NULL,
      ),
      'file' => 'uc_usps.theme.inc',
      'function' => 'theme_uc_usps_option_label',
    ),
  );
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 *
 * Adds package type to products.
 *
 * @see uc_product_form()
 */
function uc_usps_form_node_form_alter(&$form, &$form_state, $form_id) {
  $quote_config = \Drupal::config('uc_quote.settings');
  $node = $form_state->getFormObject()->getEntity();
  if (uc_product_is_product($node->bundle())) {
    $enabled = $quote_config->get('enabled') + array('usps' => FALSE, 'usps_intl' => FALSE);
    $weight = $quote_config->get('method_weight') + array('usps' => 0, 'usps_intl' => 1);

    $form['shipping']['usps'] = array(
      '#type' => 'details',
      '#title' => t('USPS product description'),
      '#weight' => $weight['usps'],
      '#tree' => TRUE,
    );
    $form['shipping']['usps']['container'] = array(
      '#type' => 'select',
      '#title' => t('Package type'),
      '#options' => \Drupal\uc_usps\USPSUtilities::packageTypes(),
      '#default_value' => isset($node->usps['container']) ? $node->usps['container'] : 'VARIABLE',
    );
  }
}

/**
 * Implements hook_node_insert().
 */
function uc_usps_node_insert($node) {
  uc_usps_node_update($node);
}

/**
 * Implements hook_node_update().
 */
function uc_usps_node_update($node) {
  if (uc_product_is_product($node)) {
    if (isset($node->usps)) {
      $usps_values = $node->usps;
      if (!$node->isNewRevision()) {
        db_delete('uc_usps_products')
          ->condition('vid', $node->getRevisionId())
          ->execute();
      }

      db_insert('uc_usps_products')
        ->fields(array(
          'vid' => $node->getRevisionId(),
          'nid' => $node->id(),
          'container' => $usps_values['container'],
        ))
        ->execute();
    }
  }
}

/**
 * Implements hook_node_load().
 */
function uc_usps_node_load($nodes) {
  $nids = array();
  foreach ($nodes as $node) {
    if (uc_product_is_product($node)) {
      $nids[] = $node->id();
    }
  }
  if (empty($nids)) {
    return;
  }

  $vids = array();
  $usps_config = \Drupal::config('uc_usps.settings');
  $shipping_type = $usps_config->get('uc_store_shipping_type');
  $shipping_types = db_query("SELECT id, shipping_type FROM {uc_quote_shipping_types} WHERE id_type = :type AND id IN (:ids[])", array(':type' => 'product', ':ids[]' => $nids))->fetchAllKeyed();

  foreach ($nids as $nid) {
    if (isset($shipping_types[$nid])) {
      $nodes[$nid]->shipping_type = $shipping_types[$nid];
    }
    else {
      $nodes[$nid]->shipping_type = $shipping_type;
    }

    if ($nodes[$nid]->shipping_type == 'small_package') {
      $vids[$nid] = $nodes[$nid]->getRevisionId();
    }
  }

  if ($vids) {
    $result = db_query("SELECT * FROM {uc_usps_products} WHERE vid IN (:vids[])", array(':vids[]' => $vids), array('fetch' => PDO::FETCH_ASSOC));
    foreach ($result as $usps) {
      $nodes[$usps['nid']]->usps = $usps;
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function uc_usps_node_delete($node) {
  db_delete('uc_usps_products')
    ->condition('nid', $node->id())
    ->execute();
}

/**
 * Implements hook_node_revision_delete().
 */
function uc_usps_node_revision_delete($node) {
  db_delete('uc_usps_products')
    ->condition('vid', $node->getRevisionId())
    ->execute();
}

/**
 * Implements hook_uc_shipping_type().
 */
function uc_usps_uc_shipping_type() {
  $quote_config = \Drupal::config('uc_quote.settings');
  $weight = $quote_config->get('type_weight', array('envelope' => -1, 'small_package' => 0));

  $types = array(
    'envelope' => array(
      'id' => 'envelope',
      'title' => t('Envelope'),
      'weight' => isset($weight['envelope']) ? $weight['envelope'] : -1,
    ),
    'small_package' => array(
      'id' => 'small_package',
      'title' => t('Small package'),
      'weight' => isset($weight['small_package']) ? $weight['small_package'] : 0,
    ),
  );

  return $types;
}

/**
 * Implements hook_uc_shipping_method().
 */
function uc_usps_uc_shipping_method() {
  $operations = array(
    'configure' => array(
      'title' => t('configure'),
      'url' => Url::fromRoute('uc_usps.settings')->toString(),
    ),
  );

  $methods = array(
    'usps_env' => array(
      'id' => 'usps_env',
      'module' => 'uc_usps',
      'title' => t('U.S. Postal Service (Envelope)'),
      'operations' => $operations,
      'quote' => array(
        'type' => 'envelope',
        'callback' => 'uc_usps_quote',
        'accessorials' => \Drupal\uc_usps\USPSUtilities::envelopeServices(),
      ),
    ),
    'usps' => array(
      'id' => 'usps',
      'module' => 'uc_usps',
      'title' => t('U.S. Postal Service (Parcel)'),
      'operations' => $operations,
      'quote' => array(
        'type' => 'small_package',
        'callback' => 'uc_usps_quote',
        'accessorials' => \Drupal\uc_usps\USPSUtilities::services(),
      ),
    ),
    'usps_intl_env' => array(
      'id' => 'usps_intl_env',
      'module' => 'uc_usps',
      'title' => t('U.S. Postal Service (Intl., Envelope)'),
      'operations' => $operations,
      'quote' => array(
        'type' => 'envelope',
        'callback' => 'uc_usps_quote',
        'accessorials' => \Drupal\uc_usps\USPSUtilities::internationalEnvelopeServices(),
      ),
      'weight' => 1,
    ),
    'usps_intl' => array(
      'id' => 'usps_intl',
      'module' => 'uc_usps',
      'title' => t('U.S. Postal Service (Intl., Parcel)'),
      'operations' => $operations,
      'quote' => array(
        'type' => 'small_package',
        'callback' => 'uc_usps_quote',
        'accessorials' => \Drupal\uc_usps\USPSUtilities::internationalServices(),
      ),
      'weight' => 1,
    ),
  );

  return $methods;
}

/******************************************************************************
 * Module Functions                                                           *
 ******************************************************************************/

/**
 * Callback for retrieving USPS shipping quote.
 *
 * @param $products
 *   Array of cart contents.
 * @param $details
 *   Order details other than product information.
 * @param $method
 *   The shipping method to create the quote.
 *
 * @return
 *   JSON object containing rate, error, and debugging information.
 */
function uc_usps_quote($products, $details, $method) {
  $usps_config = \Drupal::config('uc_usps.settings');
  $quote_config = \Drupal::config('uc_quote.settings');
  // The uc_quote AJAX query can fire before the customer has completely
  // filled out the destination address, so check to see whether the address
  // has all needed fields. If not, abort.
  $destination = (object) $details;

  // Country code is always needed.
  if (empty($destination->country)) {
    // Skip this shipping method.
    return array();
  }

  // Shipments to the US also need zone and postal_code.
  if (($destination->country == 'US') &&
      (empty($destination->zone) || empty($destination->postal_code))) {
    // Skip this shipping method.
    return array();
  }

  // USPS Production server.
  $connection_url = 'http://production.shippingapis.com/ShippingAPI.dll';

  // Initialize $debug_data to prevent PHP notices here and in uc_quote.
  $debug_data = array('debug' => NULL, 'error' => array());
  $services = array();
  $addresses = array($quote_config->get('store_default_address'));
  $packages = _uc_usps_package_products($products, $addresses);
  if (!count($packages)) {
    return array();
  }

  foreach ($packages as $key => $ship_packages) {
    $orig = $addresses[$key];
    $orig->email = uc_store_email();

    if (strpos($method['id'], 'intl') && ($destination->country != 'US')) {
      // Build XML for international rate request.
      $request = uc_usps_intl_rate_request($ship_packages, $orig, $destination);
    }
    elseif ($destination->country == 'US') {
      // Build XML for domestic rate request.
      $request = uc_usps_rate_request($ship_packages, $orig, $destination);
    }

    $account = \Drupal::currentUser();
    if ($account->hasPermission('configure quotes') && $quote_config->get('display_debug')) {
      $debug_data['debug'] .= htmlentities(urldecode($request)) . "<br />\n";
    }

    // Send request
    $result = \Drupal::httpClient()
      ->post($connection_url, NULL, $request)
      ->send();

    if ($account->hasPermission('configure quotes') && $quote_config->get('display_debug')) {
      $debug_data['debug'] .= htmlentities($result->getBody(TRUE)) . "<br />\n";
    }

    $rate_type = $usps_config->get('online_rates');
    $response = new SimpleXMLElement($result->getBody(TRUE));

    // Map double-encoded HTML markup in service names to Unicode characters.
    $service_markup = array(
      '&lt;sup&gt;&amp;reg;&lt;/sup&gt;'   => '®',
      '&lt;sup&gt;&amp;trade;&lt;/sup&gt;' => '™',
      '&lt;sup&gt;&#174;&lt;/sup&gt;'      => '®',
      '&lt;sup&gt;&#8482;&lt;/sup&gt;'     => '™',
      '**'                                 => '',
    );
    // Use this map to fix USPS service names.
    if (strpos($method['id'], 'intl')) {
      // Find and replace markup in International service names.
      foreach ($response->xpath('//Service') as $service) {
        $service->SvcDescription = str_replace(array_keys($service_markup), $service_markup, $service->SvcDescription);
      }
    }
    else {
      // Find and replace markup in Domestic service names.
      foreach ($response->xpath('//Postage') as $postage) {
        $postage->MailService = str_replace(array_keys($service_markup), $service_markup, $postage->MailService);
      }
    }


    if (isset($response->Package)) {
      foreach ($response->Package as $package) {
        if (isset($package->Error)) {
          $debug_data['error'][] = (string)$package->Error[0]->Description . '<br />';
        }
        else {
          if (strpos($method['id'], 'intl')) {
            foreach ($package->Service as $service) {
              $id = (string)$service['ID'];
              $services[$id]['label'] = t('U.S.P.S. @service', array('@service' => (string)$service->SvcDescription));
              // Markup rate before customer sees it.
              if (!isset($services[$id]['rate'])) {
                $services[$id]['rate'] = 0;
              }
              $services[$id]['rate'] += uc_usps_rate_markup((string)$service->Postage);
            }
          }
          else {
            foreach ($package->Postage as $postage) {
              $classid = (string)$postage['CLASSID'];
              if ($classid === '0') {
                if ((string)$postage->MailService == "First-Class Mail® Parcel") {
                  $classid = 'zeroParcel';
                }
                elseif ((string)$postage->MailService == "First-Class Mail® Letter") {
                  $classid = 'zeroFlat';
                }
                else {
                  $classid = 'zero';
                }
              }
              if (!isset($services[$classid]['rate'])) {
                $services[$classid]['rate'] = 0;
              }
              $services[$classid]['label'] = t('U.S.P.S. @service', array('@service' => (string)$postage->MailService));
              // Markup rate before customer sees it.
              // Rates are stored differently if ONLINE $rate_type is requested.
              // First Class doesn't have online rates, so if CommercialRate
              // is missing use Rate instead.
              if ($rate_type && !empty($postage->CommercialRate)) {
                $services[$classid]['rate'] += uc_usps_rate_markup((string)$postage->CommercialRate);
              }
              else {
                $services[$classid]['rate'] += uc_usps_rate_markup((string)$postage->Rate);
              }
            }
          }
        }
      }
    }
  }

  // Strip leading 'usps_'
  $method_services = substr($method['id'] . '_services', 5);
//$method_services is the name of the callback function
//  array_keys($method['quote']['accessorials'])

  $usps_services = array_filter($usps_config->get($method_services));
  foreach ($services as $service => $quote) {
    if (!in_array($service, $usps_services)) {
      unset($services[$service]);
    }
  }
  foreach ($services as $key => $quote) {
    if (isset($quote['rate'])) {
      $services[$key]['rate'] = $quote['rate'];
      $services[$key]['option_label'] = theme('uc_usps_option_label', array('service' => $quote['label'], 'packages' => $packages));
    }
  }

  uasort($services, 'uc_quote_price_sort');

  // Merge debug data into $services.  This is necessary because
  // $debug_data is not sortable by a 'rate' key, so it has to be
  // kept separate from the $services data until this point.
  if (isset($debug_data['debug']) ||
      (isset($debug_data['error']) && count($debug_data['error']))) {
    $services['data'] = $debug_data;
  }

  return $services;
}

/**
 * Constructs a quote request for domestic shipments.
 *
 * @param $packages
 *   Array of packages received from the cart.
 * @param $origin
 *   Delivery origin address information.
 * @param $destination
 *   Delivery destination address information.
 *
 * @return
 *   RateV4Request XML document to send to USPS.
 */
function uc_usps_rate_request($packages, $origin, $destination) {
  $usps_config = \Drupal::config('uc_usps.settings');
  $request  = '<RateV4Request USERID="' . $usps_config->get('user_id') . '">';
  $request .= '<Revision>2</Revision>';

  $rate_type = $usps_config->get('online_rates');

  $package_id = 0;
  foreach ($packages as $package) {
    $qty = $package->qty;
    for ($i = 0; $i < $qty; $i++) {
      $request .= '<Package ID="' . $package_id . '">' .
        '<Service>' . ($rate_type ? 'ONLINE' : 'ALL') . '</Service>' .
        '<ZipOrigination>' . substr(trim($origin->postal_code), 0, 5) . '</ZipOrigination>' .
        '<ZipDestination>' . substr(trim($destination->postal_code), 0, 5) . '</ZipDestination>' .
        '<Pounds>' . intval($package->pounds) . '</Pounds>' .
        '<Ounces>' . number_format($package->ounces, 1, '.', '') . '</Ounces>' .
        '<Container>' . $package->container . '</Container>' .
        '<Size>' . $package->size . '</Size>' .
        '<Width>' . $package->width . '</Width>' .
        '<Length>' . $package->length . '</Length>' .
        '<Height>' . $package->height . '</Height>' .
        '<Girth>' . $package->girth . '</Girth>' .
        '<Value>' . $package->price . '</Value>' .
        '<Machinable>' . ($package->machinable ? 'TRUE' : 'FALSE') . '</Machinable>' .
        '<ReturnLocations>TRUE</ReturnLocations>' .
        '<ShipDate Option="EMSH">' . \Drupal::service('date.formatter')->format(time(), 'custom', 'd-M-Y', 'America/New_York', 'en') . '</ShipDate>';

        // Check if we need to add any special services to this package.
        if ($usps_config->get('insurance')            ||
           $usps_config->get('delivery_confirmation') ||
           $usps_config->get('signature_confirmation')  ) {

          $request .= '<SpecialServices>';

          if ($usps_config->get('insurance')) {
            $request .= '<SpecialService>1</SpecialService>';
          }
          if ($usps_config->get('delivery_confirmation')) {
            $request .= '<SpecialService>13</SpecialService>';
          }
          if ($usps_config->get('signature_confirmation')) {
            $request .= '<SpecialService>15</SpecialService>';
          }

          $request .= '</SpecialServices>';
        }

        // Close off Package tag.
        $request .= '</Package>';

      $package_id++;
    }
  }
  $request .= '</RateV4Request>';

  return 'API=RateV4&XML=' . UrlHelper::encodePath($request);
}

/**
 * Constructs a quote request for international shipments.
 *
 * @param $packages
 *   Array of packages received from the cart.
 * @param $origin
 *   Delivery origin address information.
 * @param $destination
 *   Delivery destination address information.
 *
 * @return
 *   IntlRateRequest XML document to send to USPS.
 */
function uc_usps_intl_rate_request($packages, $origin, $destination) {
  $usps_config = \Drupal::config('uc_usps.settings');
  module_load_include('inc', 'uc_usps', 'uc_usps.countries');
  $request  = '<IntlRateV2Request USERID="' . $usps_config->get('user_id') . '">';
  $request .= '<Revision>2</Revision>';

  // USPS does not use ISO 3166 country name in some cases so we
  // need to transform ISO country name into one USPS understands.
  $shipto_country = uc_usps_country_map($destination->country);

  $package_id = 0;
  foreach ($packages as $package) {
    $qty = $package->qty;
    for ($i = 0; $i < $qty; $i++) {
      $request .= '<Package ID="' . $package_id . '">' .
        '<Pounds>' . intval($package->pounds) . '</Pounds>' .
        '<Ounces>' . ceil($package->ounces) . '</Ounces>' .
        '<MailType>All</MailType>' .
        '<ValueOfContents>' . $package->price . '</ValueOfContents>' .
        '<Country>' . $shipto_country . '</Country>' .
        '<Container>' . 'RECTANGULAR' . '</Container>' .
        '<Size>' . 'REGULAR' . '</Size>' .
        '<Width>' . '</Width>' .
        '<Length>' . '</Length>' .
        '<Height>' . '</Height>' .
        '<Girth>' . '</Girth>' .
        '<OriginZip>' . substr(trim($origin->postal_code), 0, 5) . '</OriginZip>';

        // Check if we need to add any special services to this package.
        if ($usps_config->get('insurance')) {
          $request .= '<ExtraServices><ExtraService>1</ExtraService></ExtraServices>';
        }

        // Close off Package tag.
        $request .= '</Package>';

      $package_id++;
    }
  }
  $request .= '</IntlRateV2Request>';

  $request = 'API=IntlRateV2&XML=' . UrlHelper::encodePath($request);
  return $request;
}

/**
 * Modifies the rate received from USPS before displaying to the customer.
 *
 * @param $rate
 *   Shipping rate without any rate markup.
 *
 * @return
 *   Shipping rate after markup.
 */
function uc_usps_rate_markup($rate) {
  $usps_config = \Drupal::config('uc_usps.settings');
  $markup = trim($usps_config->get('rate_markup'));
  $type   = $usps_config->get('rate_markup_type');

  if (is_numeric($markup)) {
    switch ($type) {
      case 'percentage':
        return $rate + $rate * floatval($markup) / 100;
      case 'multiplier':
        return $rate * floatval($markup);
      case 'currency':
        return $rate + floatval($markup);
    }
  }
  else {
    return $rate;
  }
}

/**
 * Modifies the weight of shipment before sending to USPS for a quote.
 *
 * @param $weight
 *   Shipping weight without any weight markup.
 *
 * @return
 *   Shipping weight after markup.
 */
function uc_usps_weight_markup($weight) {
  $usps_config = \Drupal::config('uc_usps.settings');
  $markup = trim($usps_config->get('weight_markup'));
  $type   = $usps_config->get('weight_markup_type');

  if (is_numeric($markup)) {
    switch ($type) {
      case 'percentage':
        return $weight + $weight * floatval($markup) / 100;

      case 'multiplier':
        return $weight * floatval($markup);

      case 'mass':
        return $weight + floatval($markup);
    }
  }
  else {
    return $weight;
  }
}

/**
 * Organizes products into packages for shipment.
 *
 * @param $products
 *   An array of product objects as they are represented in the cart or order.
 * @param &$addresses
 *   Reference to an array of addresses which are the pickup locations of each
 *   package. They are determined from the shipping addresses of their
 *   component products.
 *
 * @return
 *   Array of packaged products. Packages are separated by shipping address and
 *   weight or quantity limits imposed by the shipping method or the products.
 */
function _uc_usps_package_products($products, &$addresses) {
  $last_key = 0;
  $packages = array();
  $usps_config = \Drupal::config('uc_usps.settings');
  if ($usps_config->get('all_in_one') && count($products) > 1) {
    // "All in one" packaging strategy.
    // Only need to do this if more than one product line item in order.
    $packages[$last_key] = array(0 => _uc_usps_new_package());
    foreach ($products as $product) {
      if ($product->nid) {
        // Packages are grouped by the address from which they will be
        // shipped. We will keep track of the different addresses in an array
        // and use their keys for the array of packages.

        $key = NULL;
        $address = uc_quote_get_default_shipping_address($product->nid);
        foreach ($addresses as $index => $value) {
          if ($address->isSamePhysicalLocation($value)) {
            // This is an existing address.
            $key = $index;
            break;
          }
        }

        if (!isset($key)) {
          // This is a new address. Increment the address counter $last_key
          // instead of using [] so that it can be used in $packages and
          // $addresses.
          $addresses[++$last_key] = $address;
          $key = $last_key;
          $packages[$key] = array(0 => _uc_usps_new_package());
        }
      }

      // Grab some product properties directly from the (cached) product
      // data. They are not normally available here because the $product
      // object is being read out of the $order object rather than from
      // the database, and the $order object only carries around a limited
      // number of product properties.
      $temp = node_load($product->nid);
      $product->length = $temp->length;
      $product->width = $temp->width;
      $product->height = $temp->height;
      $product->length_units = $temp->length_units;
      $product->usps['container'] = isset($temp->usps['container']) ? $temp->usps['container'] : 'VARIABLE';

      $packages[$key][0]->price += $product->price * $product->qty;
      $packages[$key][0]->weight += $product->weight * $product->qty * uc_weight_conversion($product->weight_units, 'lb');
    }
    foreach ($packages as $key => $package) {
      $packages[$key][0]->pounds = floor($package[0]->weight);
      $packages[$key][0]->ounces = LB_TO_OZ * ($package[0]->weight - $packages[$key][0]->pounds);
      $packages[$key][0]->container = 'VARIABLE';
      $packages[$key][0]->size = 'REGULAR';
      // Packages are "machinable" if heavier than 6oz. and less than 35lbs.
      $packages[$key][0]->machinable = (
        ($packages[$key][0]->pounds == 0 ? $packages[$key][0]->ounces >= 6 : TRUE) &&
        $packages[$key][0]->pounds <= 35 &&
        ($packages[$key][0]->pounds == 35 ? $packages[$key][0]->ounces == 0 : TRUE)
      );
      $packages[$key][0]->qty = 1;
    }
  }
  else {
    // !$usps_config->get('all_in_one') || count($products) = 1
    // "Each in own" packaging strategy, or only one product line item in order.
    foreach ($products as $product) {
      if ($product->nid) {
        $address = uc_quote_get_default_shipping_address($product->nid);
        if (in_array($address, $addresses)) {
          // This is an existing address.
          foreach ($addresses as $index => $value) {
            if ($address == $value) {
              $key = $index;
              break;
            }
          }
        }
        else {
          // This is a new address.
          $addresses[++$last_key] = $address;
          $key = $last_key;
        }
      }
      if (!isset($product->pkg_qty) || !$product->pkg_qty) {
        $product->pkg_qty = 1;
      }
      $num_of_pkgs = (int)($product->qty / $product->pkg_qty);
      if ($num_of_pkgs) {
        $package = clone $product;
        $package->description = $product->model;
        $weight = $product->weight * $product->pkg_qty;
        switch ($product->weight_units) {
          case 'g':
            // Convert to kg and fall through.
            $weight = $weight * G_TO_KG;
          case 'kg':
            // Convert to lb and fall through.
            $weight = $weight * KG_TO_LB;
          case 'lb':
            $package->pounds = floor($weight);
            $package->ounces = LB_TO_OZ * ($weight - $package->pounds);
            break;
          case 'oz':
            $package->pounds = floor($weight * OZ_TO_LB);
            $package->ounces = $weight - $package->pounds * LB_TO_OZ;
            break;
        }

        // Grab some product properties directly from the (cached) product
        // data. They are not normally available here because the $product
        // object is being read out of the $order object rather than from
        // the database, and the $order object only carries around a limited
        // number of product properties.
        $temp = node_load($product->nid);
        $product->length = $temp->length;
        $product->width = $temp->width;
        $product->height = $temp->height;
        $product->length_units = $temp->length_units;
        $product->usps['container'] = isset($temp->usps['container']) ? $temp->usps['container'] : 'VARIABLE';

        $package->container = $product->usps['container'];
        $length_conversion = uc_length_conversion($product->length_units, 'in');
        $package->length = max($product->length, $product->width) * $length_conversion;
        $package->width = min($product->length, $product->width) * $length_conversion;
        $package->height = $product->height * $length_conversion;
        if ($package->length < $package->height) {
          list($package->length, $package->height) = array($package->height, $package->length);
        }
        $package->girth = 2 * $package->width + 2 * $package->height;
        $package->size = $package->length <= 12 ? 'REGULAR' : 'LARGE';
        $package->machinable = (
          $package->length >= 6 && $package->length <= 34 &&
          $package->width >= 0.25 && $package->width <= 17 &&
          $package->height >= 3.5 && $package->height <= 17 &&
          ($package->pounds == 0 ? $package->ounces >= 6 : TRUE) &&
          $package->pounds <= 35 &&
          ($package->pounds == 35 ? $package->ounces == 0 : TRUE)
        );
        $package->price = $product->price * $product->pkg_qty;
        $package->qty = $num_of_pkgs;
        $packages[$key][] = $package;
      }
      $remaining_qty = $product->qty % $product->pkg_qty;
      if ($remaining_qty) {
        $package = clone $product;
        $package->description = $product->model;
        $weight = $product->weight * $remaining_qty;
        switch ($product->weight_units) {
          case 'g':
            // Convert to kg and fall through.
            $weight = $weight * G_TO_KG;
          case 'kg':
            // Convert to lb and fall through.
            $weight = $weight * KG_TO_LB;
          case 'lb':
            $package->pounds = floor($weight);
            $package->ounces = LB_TO_OZ * ($weight - $package->pounds);
            break;
          case 'oz':
            $package->pounds = floor($weight * OZ_TO_LB);
            $package->ounces = $weight - $package->pounds * LB_TO_OZ;
            break;
        }
        $package->container = $product->usps['container'];
        $length_conversion = uc_length_conversion($product->length_units, 'in');
        $package->length = max($product->length, $product->width) * $length_conversion;
        $package->width = min($product->length, $product->width) * $length_conversion;
        $package->height = $product->height * $length_conversion;
        if ($package->length < $package->height) {
          list($package->length, $package->height) = array($package->height, $package->length);
        }
        $package->girth = 2 * $package->width + 2 * $package->height;
        $package->size = $package->length <= 12 ? 'REGULAR' : 'LARGE';
        $package->machinable = (
          $package->length >= 6 && $package->length <= 34 &&
          $package->width >= 0.25 && $package->width <= 17 &&
          $package->height >= 3.5 && $package->height <= 17 &&
          ($package->pounds == 0 ? $package->ounces >= 6 : TRUE) &&
          $package->pounds <= 35 &&
        ($package->pounds == 35 ? $package->ounces == 0 : TRUE)
        );
        $package->price = $product->price * $remaining_qty;
        $package->qty = 1;
        $packages[$key][] = $package;
      }
    }
  }
  return $packages;
}

/**
 * Pseudo-constructor to set default values of a package.
 */
function _uc_usps_new_package() {
  $package = new stdClass();

  $package->price = 0;
  $package->qty = 1;
  $package->pounds = 0;
  $package->ounces = 0;
  $package->container = 0;
  $package->size = 0;
  $package->machinable = TRUE;

  $package->length = 0;
  $package->width = 0;
  $package->height = 0;
  $package->girth = 0;

//  $package->length_units = 'in';
//  $package->weight_units = 'lb';

  return $package;
}
