<?php

/**
 * @file
 * Contains global Ubercart functions and store administration functionality.
 */


/**
 * Returns an array of country files that can be installed or updated.
 *
 * @return array
 *   Associative array keyed by the country's ISO 3166-1 numeric country
 *   code. Each key holds an array of two elements, 'file' and 'version',
 *   containing the file name for that country's .cif file and the .cif
 *   file version, respectively.
 */
function uc_country_import_list() {
  $dir = drupal_get_path('module', 'uc_country') . '/countries/';

  $countries = array();
  if (is_dir($dir)) {
    if ($dh = opendir($dir)) {
      while (($file = readdir($dh)) !== FALSE) {
        switch (filetype($dir . $file)) {
          case 'file':
            if (substr($file, -4, 4) == '.cif') {
              $pieces = explode('_', substr($file, 0, strlen($file) - 4));
              $country_id = intval($pieces[count($pieces) - 2]);
              $version = $pieces[count($pieces) - 1];

              if (!isset($countries[$country_id])) {
                $countries[$country_id]['version'] = $version;
                $countries[$country_id]['file'] = $file;
              }
              else {
                if ($version > $countries[$country_id]['version']) {
                  $countries[$country_id]['version'] = $version;
                  $countries[$country_id]['file'] = $file;
                }
              }
            }
            break;
        }
      }
      closedir($dh);
    }
  }

  return $countries;
}

/**
 * Returns a list of all installed/available countries.
 *
 * @return array
 *   Associative array keyed by the country's ISO 3166-1 alpha_2 country
 *   code and containing the translated ISO 3166-1 country name.
 */
function uc_country_option_list() {
  $countries = \Drupal::entityManager()->getStorage('uc_country')->loadByProperties(['status' => TRUE]);
  $country_names = [];
  foreach ($countries as $alpha_2 => $country) {
    $country_names[$alpha_2] = t($country->name);
  }
  natcasesort($country_names);
  return $country_names;
}

/**
 * Helper function to return zone options, grouped by country.
 */
function uc_zone_option_list() {
  $options = array();
  $countries = \Drupal::entityManager()->getStorage('uc_country')->loadByProperties(['status' => TRUE]);
  foreach ($countries as $country) {
    if (!empty($country->zones)) {
      $options[t($country->name)] = $country->zones;
    }
  }
  uksort($options, 'strnatcasecmp');

  return $options;
}
