<?php

/**
 * @file
 * Ubercart Catalog module.
 *
 * Provides classification and navigation product nodes using taxonomy. When
 * installed, this module creates a vocabulary named "Product Catalog" and
 * stores the vocabulary id for future use. The user is responsible for
 * maintaining the terms in the taxonomy, though the Catalog will find products
 * not listed in it.
 */

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\node\NodeTypeInterface;

/**
 * Implements hook_help().
 */
function uc_catalog_help($path, $arg) {
  switch ($path) {
    case 'admin/store/products/orphans':
      return '<p>' . t('Orphaned products are products that you have created but not yet assigned to a category in your product catalog. All such products will appear as links below that you can follow to edit the product listings to assign them to categories.') . '</p>';

    case 'admin/store/settings/catalog':
      if (!module_exists('views_ui')) {
        return '<p>' . t('<a href="@modules">Enable the Views UI module</a> to edit the catalog display.', array('@modules' => url('admin/modules', array('fragment' => 'edit-modules-views')))) . '</p>';
      }
      break;
  }
}

/**
 * Implements hook_menu().
 */
function uc_catalog_menu() {
  $items['admin/store/settings/catalog'] = array(
    'title' => 'Catalog',
    'description' => 'Configure the product catalog pages.',
    'route_name' => 'uc_catalog.settings',
  );
  $items['admin/store/products/orphans'] = array(
    'title' => 'Find orphaned products',
    'description' => 'Find products that have not been categorized.',
    'page callback' => 'uc_catalog_orphaned_products',
    'access arguments' => array('administer catalog'),
    'weight' => -4,
    'file' => 'uc_catalog.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_link_defaults().
 */
function uc_catalog_links_menu_link_defaults() {
  $links['uc_catalog.admin.store.settings.catalog'] = array(
    'link_title' => 'Catalog',
    'description' => 'Configure the product catalog pages.',
    'route_name' => 'uc_catalog.settings',
    'parent' => 'uc_store.admin.store.settings',
  );

  return $links;
}

/**
 * Implements hook_permission().
 */
function uc_catalog_permission() {
  return array(
    'administer catalog' => array(
      'title' => t('Administer catalog'),
    ),
    'view catalog' => array(
      'title' => t('View catalog'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function uc_catalog_theme() {
  return array(
    'uc_catalog_block' => array(
      'variables' => array('menu_tree' => NULL),
      'file' => 'uc_catalog.theme.inc',
    ),
    'uc_catalog_item' => array(
      'variables' => array(
        'here' => NULL,
        'link' => NULL,
        'lis' => NULL,
        'expand' => NULL,
        'inpath' => NULL,
        'count_children' => NULL,
      ),
      'file' => 'uc_catalog.theme.inc',
    ),
  );
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function uc_catalog_form_taxonomy_vocabulary_form_alter(&$form, &$form_state, $form_id) {
  $vid = \Drupal::config('uc_catalog.settings')->get('vocabulary');
  $vocabulary = $form_state['controller']->getEntity();
  if ($vid == $vocabulary->id()) {
    $form['help_catalog_vocab'] = array(
      '#markup' => t('This is the designated catalog vocabulary. Some of the normal vocabulary options have been removed.'),
      '#weight' => -1,
    );
    // Catalog vocabulary always has single hierarchy.
    $form['hierarchy']['#value'] = TAXONOMY_HIERARCHY_SINGLE;
    // Do not allow the catalog vocabulary to be deleted.
    $form['actions']['delete']['#access'] = FALSE;
    // Do not allow the catalog vid to be changed.
    $form['vid']['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function uc_catalog_entity_bundle_info_alter(&$bundles) {
  // Take over URI construction for taxonomy terms that are catalog categories.
  if ($vid = \Drupal::config('uc_catalog.settings')->get('vocabulary')) {
    if (isset($bundles['taxonomy_term'][$vid])) {
      $bundles['taxonomy_term'][$vid]['uri_callback'] = 'uc_catalog_uri';
    }
  }
}

/**
 * Entity URI callback used in uc_catalog_entity_bundle_info_alter().
 */
function uc_catalog_uri($category) {
  return 'catalog/' . $category->id();
}

/**
 * Preprocesses the catalog block output.
 */
function uc_catalog_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'uc_catalog' && $variables['label'] && $variables['configuration']['link_title']) {
    $variables['label'] = l($variables['label'], 'catalog');
  }
}

/**
 * Implements hook_uc_store_status().
 *
 * Provides status information about the "Product Catalog" and products not
 * listed in the catalog.
 */
function uc_catalog_uc_store_status() {
  $field = field_info_field('node', 'taxonomy_catalog');
  if (!$field) {
    return array(array(
      'status' => 'error',
      'title' => t('Catalog field'),
      'desc' => t('The catalog taxonomy reference field is missing. <a href="!url">Click here to create it</a>.', array('!url' => url('admin/store/settings/catalog/repair'))),
    ));
  }

  $statuses = array();
  $cat_id = \Drupal::config('uc_catalog.settings')->get('vocabulary');
  $catalog = taxonomy_vocabulary_load($cat_id);
  if ($catalog) {
    // Don't display a status if the taxonomy_index table has no data.
    if (\Drupal::config('taxonomy.settings')->get('maintain_index_table')) {
      $statuses[] = array('status' => 'ok', 'title' => t('Catalog vocabulary'),
        'desc' => t('Vocabulary !name has been identified as the Ubercart catalog.', array('!name' => l($catalog->label(), 'admin/structure/taxonomy/manage/' . $catalog->vid)))
      );

      $product_types = uc_product_types();
      $types = array_intersect($product_types, $field->getBundles());
      $result = db_query("SELECT COUNT(DISTINCT n.nid) FROM {node} n LEFT JOIN {taxonomy_index} ti ON n.nid = ti.nid LEFT JOIN {taxonomy_term_data} td ON ti.tid = td.tid WHERE n.type IN (:types) AND ti.tid IS NULL AND td.vid = :vid", array(':types' => $types, ':vid' => $catalog->vid));
      if ($excluded = $result->fetchField()) {
        $description = \Drupal::translation()->formatPlural($excluded, 'There is 1 product not listed in the catalog.', 'There are @count products not listed in the catalog.')
          . t('Products are listed by assigning a category from the <a href="!cat_url">Product Catalog</a> vocabulary to them.', array('!cat_url' => url('admin/structure/taxonomy/manage/' . $catalog->machine_name)));
        $terms = db_query("SELECT COUNT(1) FROM {taxonomy_term_data} WHERE vid = :vid", array(':vid' => $catalog->vid))->fetchField();
        if ($terms) {
          $description .= ' ' . l(t('Find orphaned products here.'), 'admin/store/products/orphans');
        }
        else {
          $description .= ' ' . l(t('Add terms for the products to inhabit.'), 'admin/structure/taxonomy/manage/' . $catalog->vid . '/add');
        }
        $statuses[] = array(
          'status' => 'warning',
          'title' => t('Unlisted products'),
          'desc' => $description,
        );
      }
    }
  }
  else {
    $statuses[] = array(
      'status' => 'error',
      'title' => t('Catalog vocabulary'),
      'desc' => t('No vocabulary has been recognized as the Ubercart catalog. Choose one on <a href="!admin_catalog">this page</a> or add one on the <a href="!admin_vocab">taxonomy admin page</a> first, if needed.', array('!admin_catalog' => url('admin/store/settings/catalog'), '!admin_vocab' => url('admin/structure/taxonomy'))),
    );
  }

  return $statuses;
}

/**
 * Implements hook_node_type_insert().
 *
 * Adds product node types to the catalog vocabulary as they are created.
 */
function uc_catalog_node_type_insert(NodeTypeInterface $type) {
  $settings = $type->getModuleSettings('uc_product');
  if (!empty($settings['product'])) {
    uc_catalog_add_node_type($type->id());
  }
}

/**
 * Emulates Drupal's menu system, but based around the catalog taxonomy.
 *
 * @param $branch
 *   A treeNode object. Determines if the URL points to itself, or possibly one
 *   of its children, if present. If the URL points to itself or one of its
 *   products, it displays its name and expands to show its children, otherwise
 *   displays a link and a count of the products in it. If the URL points to
 *   one of its children, it still displays a link and product count, but must
 *   still be expanded. Otherwise, it is collapsed and a link.
 *
 * @return
 *   An array whose first element is true if the treeNode is in hierarchy of
 *   the URL path. The second element is the HTML of the list item of itself
 *   and its children.
 */
function _uc_catalog_navigation($branch) {
  static $types;

  if (empty($types)) {
    $types = uc_product_types();
  }

  $query = Drupal::entityQuery('node')
    ->condition('type', $types)
    ->condition('status', 1) // Don't include unpublished products.
    ->condition('taxonomy_catalog.target_id', $branch->tid)
    ->count();
  $num = $query->execute();

  $branch_path = uc_catalog_path($branch);
  // Determine if the URL points to this term.
  $here = current_path() == $branch_path;

  // Determine whether to expand menu item.
  $inpath = $here;
  $request = \Drupal::request();
  if ($request->attributes->has('node')) {
    $node = $request->attributes->get('node');
    if (isset($node->taxonomy_catalog)) {
      $inpath = FALSE;
      $parents = taxonomy_term_load_parents_all($node->taxonomy_catalog->value);
      foreach ($parents as $parent) {
        if ($parent->id() == $branch->tid) {
          $inpath = TRUE;
        }
      }
    }
  }

  $lis = array();
  $expand = variable_get('uc_catalog_expand_categories', FALSE);
  if ($expand || count($branch->children)) {
    foreach ($branch->children as $twig) {
      // Expand if children are in the menu path. Capture their output.
      list($child_in_path, $lis[], $child_num) = _uc_catalog_navigation($twig);
      $num += $child_num;
      if ($child_in_path) {
        $inpath = $child_in_path;
      }
    }
  }

  // No nodes in category or descendants. Not in path and display nothing.
  if (!$num) {
    return array(FALSE, '', 0);
  }

  // Checks to see if node counts are desired in navigation.
  $num_text = '';
  if (variable_get('uc_catalog_block_nodecount', TRUE)) {
    $num_text = ' (' . $num . ')';
  }
  $link = l($branch->name . $num_text, $branch_path);

  $output = theme('uc_catalog_item', array(
    'here' => $here,
    'link' => $link,
    'lis' => $lis,
    'expand' => $expand,
    'inpath' => $inpath,
    'count_children' => count($branch->children),
  ));

  // Tell parent category your status, and pass on output.
  return array($inpath, $output, $num);
}

/**
 * Creates paths to the catalog from taxonomy term.
 */
function uc_catalog_path($term) {
  return 'catalog/' . $term->tid;
}

/**
 * Adds a catalog taxonomy reference field to the specified node type.
 */
function uc_catalog_add_node_type($type) {
  $vid = \Drupal::config('uc_catalog.settings')->get('vocabulary');

  $field = field_info_field('node', 'taxonomy_catalog');
  if (!$field) {
    $field = entity_create('field_config', array(
      'entity_type' => 'node',
      'name' => 'taxonomy_catalog',
      'type' => 'taxonomy_term_reference',
      'cardinality' => FieldDefinitionInterface::CARDINALITY_UNLIMITED,
      'settings' => array(
        'allowed_values' => array(
          array(
            'vocabulary' => $vid,
            'parent' => 0,
          ),
        ),
      ),
    ));
    $field->save();
  }

  $instance = field_info_instance('node', 'taxonomy_catalog', $type);
  if (!$instance) {
    $instance = entity_create('field_instance_config', array(
      'field_name' => 'taxonomy_catalog',
      'entity_type' => 'node',
      'bundle' => $type,
      'label' => t('Catalog'),
    ));
    $instance->save();

    entity_get_form_display('node', $type, 'default')
      ->setComponent('taxonomy_catalog', array(
        'type' => 'options_select',
      ))
      ->save();

    entity_get_display('node', $type, 'default')
      ->setComponent('taxonomy_catalog')
      ->save();
  }
}

/**
 * Sets up a default image field on the Catalog vocabulary.
 */
function uc_catalog_add_image_field() {
  $field = field_info_field('taxonomy_term', 'uc_catalog_image');

  if (!$field) {
    $field = entity_create('field_config', array(
      'entity_type' => 'taxonomy_term',
      'name' => 'uc_catalog_image',
      'type' => 'image',
    ));
    $field->save();
  }

  $instance = field_info_instance('taxonomy_term', 'uc_catalog_image', 'catalog');

  // Only add the instance if it doesn't exist. Don't overwrite any changes.
  if (!$instance) {
    $instance = entity_create('field_instance_config', array(
      'field_name' => 'uc_catalog_image',
      'entity_type' => 'taxonomy_term',
      'bundle' => 'catalog',
      'label' => t('Image'),
    ));
    $instance->save();

    entity_get_form_display('taxonomy_term', 'catalog', 'default')
      ->setComponent('uc_catalog_image', array(
        'type' => 'image_image',
      ))
      ->save();

    entity_get_display('taxonomy_term', 'catalog', 'default')
      ->setComponent('uc_catalog_image', array(
        'label' => 'hidden',
        'type' => 'image',
        'settings' => array(
          'image_link' => 'content',
          'image_style' => 'uc_category',
        ),
      ))
      ->save();
  }
}
